### ISSUE TITLE
no permission to access user information is configured for [cilent id]

### ISSUE THREAD

**Issue by bigerock** [AzureAD/azure-activedirectory-library-for-js#101]
i'm not able to get past the authentication phase to load my pages. it's giving this information in the console:

No permission to access user information is configured for '[client id]' application, or it is expired or revoked. 

Any ideas what i might be missing?

i'm following this for the client/web api example: https://github.com/AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet

**Comment by omercs** [comment]
You need to setup the permissions for your app at AAD portal.

You can read more here: https://msdn.microsoft.com/en-us/library/azure/dn132599.aspx

**Comment by omercs** [comment]
Is this still an issue?

**Comment by bigerock** [comment]
it likely still is, but i dropped it for now.

**Comment by nimatra** [comment]
I'm hitting this issue on Windows 10. I have set the permissions in AD on Azure.

**Comment by polita** [comment]
If you haven't configured your outlook.com account as a guest in your tenant, ADAL.js doesn't support using your Microsoft Account for login. If you have configured your outlook.com account as a guest, this should work as long as you use the intended tenant endpoint rather than the common endpoint. Please give us a little more information if this doesn't answer your question.
