### ISSUE TITLE
ProtectedResourceInterceptor always overrides Authorization header 

### ISSUE THREAD

**Issue by bpatra** [AzureAD/azure-activedirectory-library-for-js#127]
I ran into the following problem with adal-angular when trying to request another web API.

Precisely, when I am successfully authenticated using ADAL then, if I try to request another WEB API, (using angular's $http) the request's *Authorization* header is overridden by the *ProtectedResourceInterceptor*. The later one will put its *storedToken* for *Bearer* in *Authorization* header. Consequently, my request (that has nothing to do with my ADAL authentication) fails with 401.

The culprit code is seems to be here (line 277 to 293 on 7a5480e7ee2158d3a9d1145cfe35852b414f6282)

        var resource = authService.getResourceForEndpoint(config.url);
        var tokenStored = authService.getCachedToken(resource);
        var isEndpoint = false;
        if (tokenStored) {
	        // check endpoint mapping if provided
	        config.headers.Authorization = 'Bearer ' + tokenStored;
	        return config;
        } else {
        
	        if (authService.config) {
		        for (var endpointUrl in authService.config.endpoints) {
			        if (config.url.indexOf(endpointUrl) > -1) {
				        isEndpoint = true;
			        }
		        }
	        }

Even if *config.url* has nothing to do with endpoints used by ADAL, the boolean value *tokenStored* is true resulting in the override I mentioned before.

However if you looked at the piece of code after the *else* statement, you will notice a check. Indeed, we check if the url used is actually part of the ADAL's used endpoints. My suggestion would be to move up this check and do nothing is *isEndpoint = false*.

 I tested with both 1.0.1 release and master's HEAD 7a5480e7ee2158d3a9d1145cfe35852b414f6282. I would gladly try to pull request the fix. 

Thank you.

Note: I am newbie to angular so I may be wrong with what I am posting here.

**Comment by omercs** [comment]
@bpatra: Interceptor always attaches token to app itself. Calls related to the app's url will have token in the header. We don't have a list of endpoints to skip the interceptor. You can skip interceptor for all endpoints if you don't define in the init.
```js
adalAuthenticationServiceProvider.init(
        {
            // Config to specify endpoints and similar for your app
            tenant: "52d4b072-9470-49fb-8721-bc3a1c9912a1", // Optional by default, it sends common
            clientId: "e9a5a8b6-8af7-4719-9821-0deef255f68e", // Required
            //localLoginUrl: "/login",  // optional
            //redirectUri : "your site", optional
            endpoints: endpoints  // If you need to send CORS api requests.
        } // don't define httpprovider to skip interceptor
        );
```

We could think about adding support to skip specific urls. Your app should use Endpoints to support CORS api calls.

 Is your webapi on same url as config.url? Is it in another domain?

**Comment by tushargupta51** [comment]
@bpatra Is this still an active issue for you? 

`var resource = authService.getResourceForEndpoint(config.url);`

resource should be non-null if config.url is:
1. an endpoint configured in adal.config
2. matches app's backend domain
3. relative url, in which case it is assumed to be a request to application

If none of the above is true, resource will be null and we dont attach any token to auth header.

Let us know if you still see this issue with the latest version of adal.

**Comment by sandor11** [comment]
@tushargupta51 I may have a misunderstanding of when and where to use the adal code, as this is my first attempt at an implementation, however I have an issue with the Interceptor also.

My web app has its own API, which is actually running on the same box as our front end web server. This means, that regardless of having configured an API Endpoint of `https://graph.microsoft.com` when I am making backend API calls e.g. `/api/user/notificactions` the interceptor believes it has a resource (which is my clientId), tries to acquire a token which errors because `User login is required`.

In my application flow, I only want to trigger login when a user selects to link their account, and I am not using Route level protection. This interceptor hijacked and killed my entire backend, due to what I believe are incorrect assumptions.

If I have configured an endpoint, then I only want the interceptor to run on that host, no others.

From line 724 in adal.js I changed the following

```
if (this.config && this.config.endpoints) {
        for (var configEndpoint in this.config.endpoints) {
            // configEndpoint is like /api/Todo requested endpoint can be /api/Todo/1
            if (endpoint.indexOf(configEndpoint) > -1) {
                return this.config.endpoints[configEndpoint];
            }
        }
        return null;
    }
```
Note, that if no endpoints match my configured ones, it will allow the Interceptor to return the config and move on. My application now works again and I can authorize a user as required. Have I missed something? Why does adal.js try to take over every local request?

**Comment by tushargupta51** [comment]
@sandor11 Be default, all the requests to app's backend are secure, which means interceptor will try to attach a token to the outgoing requests. We are thinking of providing an extensibility point where users can add list of app's backend url (relative or full urls) to be skipped by interceptor.

**Comment by sandor11** [comment]
@tushargupta51 That would help some situations. In our app, we only utilize the Graph API for very limited percentage of functionality. Being requwired to list every backend url, api related or otherwise would not be maintainable as every time we created a new API route, our process would have to include adding that to the excluded routes table for `adal`. I would rather see a boolean flag which says to ignore endpoints not in the config.

That is more like what my code changes are doing and it works for our situation. I am not using this product to secure our entire app, we have implemented JWT to secure our own API, at the moment the API and the web server live together so calls are relative. We only need the interceptor to fire when we are making request to our configured endpoint(s).

**Comment by tushargupta51** [comment]
@sandor11 You do not have to specify all of the backend urls. The matching logic sees if the configured anonymous endpoint/relative url is part of the an app's backend url. For example, if you add "app/views" to anonymous endpoints lists, it skips all these urls - "app/views", "app/views/abc". So, if only urls that you want interceptor to act on are the ones configured in the endpoints list then you can specify a very generic/high level backend uri, e,g "/" will ignore all of the requests send to backend. Another option could be to plug in your own httpInterceptor.

**Comment by sandor11** [comment]
@tushargupta51 ok, got it. That would be sufficient for our purposes.

**Comment by tushargupta51** [comment]
1.0.10 fixes this. Please let me know, if you still see issues. Use `config.AnonymousEndpoints` for uri you want interceptor to skip.
