### ISSUE TITLE
Make adal.js working within an iFrame sandboxed environment

### ISSUE THREAD

**Issue by bpatra** [AzureAD/azure-activedirectory-library-for-js#129]
This is more a feature request, an enhancement, than an issue. Actually, I think adal.js should be working when embedded within an [html5 sandboxed iframe](http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/).

Wait! this is not as stupid as it looks because sandboxed iframe is the runtime environment of the new [app for office model](https://msdn.microsoft.com/en-us/library/office/jj220082.aspx). It would be really nice to have access to the azure ad (and therefore office 365 REST API) from an office 365 app. [See documentation here](https://msdn.microsoft.com/en-us/library/office/fp161165.aspx)

Currently adal.js is not working, because of the use of _window.location.replace(urlNavigate);_ line 361 7a5480e7ee2158d3a9d1145cfe35852b414f6282 of adal.js
Actually, it behaves differently in a sandboxed environment and creates a popup or displays an error message depending on the browser's implementation.

Fortunately, we do not require the enhancement to work in the most restrictive sandboxed environment where javascript is disabled. I remarked that the sandbox parameters in the app for office are the following ones \* sandbox="allow-scripts allow-forms allow-same-origin ms-allow-popups allow-popups"*

I started a sample here where I created a replication environment (that does not require office) with just a sandboxed iframe. You can view it on [this remote branch on my fork](https://github.com/bpatra/azure-activedirectory-library-for-js/tree/sandboxed-iframe).I will try to provide a fix because I need it to release my app.

Any help or thought is welcome.

Thank you very much.

**Comment by bpatra** [comment]
Create a [blog post](http://benoitpatra.com/2015/05/28/implementing-the-oauth-2-0-flow-in-app-for-office-sandboxed-environment/) about the 'only' solution I found to overcome this problem.
Asked also the social msdn about the [security restrictions](https://social.msdn.microsoft.com/Forums/office/en-US/c0d9d148-3242-4a0c-902c-245f406f3371/what-are-the-precise-restrictions-for-the-iframe-and-the-browser-in-apps-for-office-?forum=appsforoffice) and the implementation of the [OAUTH in sandboxed environment](https://social.msdn.microsoft.com/Forums/office/en-US/c36a1706-e1b8-4d29-96ce-b52fe774c692/what-is-the-recommended-solution-for-implementing-the-oauth-20-flow-in-sandboxed-app-for-office?forum=appsforoffice)

**Comment by Hihaj** [comment]
@bpatra I've been experimenting with something very similar to the workaround you describe in your blog post, but for use within Dynamics CRM Online (and without knowing about your efforts). My solution is a bit different though; I use a custom `displayCall` function to open a popup window with the Azure AD login page (which is supported by adal.js) and let the parent window periodically check the popup window's hash to see if the login flow has completed. Then I needed to tweak the `handleWindowCallback` function of the AuthenticationContext somewhat to allow for the hash to be passed as an argument (instead of it always using `window.location.hash`) + prevent it from always overwriting `window.location`.

Moreover I add an event handler in the main window (which would be loaded by Dynamics CRM in this specific use case) that listens for "get user" messages using the `window.postMessage` API, uses adal.js to get user tokens/user info and returns them to the message sender. This way, any iframed pages (or even scripts on the same page) can request tokens consistently and all the popup and hash checking is handled by a central component.

I'm considering sending a pull request for this pretty minor change to adal.js - I see no reason why it should assume that the login callback always happens in the same window.

**Comment by bpatra** [comment]
@Hihaj this is really interesting. Your PR #160 introduced few changes in adal.js code and looks very neat. I would be interested to see how you use it in your Dynamics app.

**Comment by Hihaj** [comment]
@bpatra Have a look at the gist I linked to in the PR comments - it's not a complete solution, but it shows how a central script can request user tokens using popup windows instead of the main window. Expanding on this, one could pretty easily add an event listener in the main window that embedded (iframed) apps can send user token requests to.

**Comment by Hihaj** [comment]
@bpatra In Dynamics CRM specifically, `window.open` is not the best choice though - it opens a window in a separate process unavailable to the script when run in the Outlook client. Instead, I would use `Xrm.Utility.openWebResource` with a custom "redirect page" (HTML web resource that redirects to a url passed in as the `data` query parameter) - this ensures that the popup is accessible to the script, which is needed in order for it to extract the hash after a successful login.

**Comment by hitendramalviya** [comment]
Even I am also running into same issue. @Hihaj how can we use `Xrm.Utility.openWebResource` instead of `window.open`.

**Comment by Hihaj** [comment]
@hitendramalviya Create a HTML web resource containing a script that reads a url from the `data` querystring parameter, then redirects (using the `window.location` API) to that url. So instead of `window.open('https://example.com')` you would use `Xrm.Utility.openWebResource('redirect.html?data=https://example.com')` (though the `data` parameter value would have to be url-encoded (use `encodeURIComponent`)).

**Comment by tushargupta51** [comment]
We added support for pop up based authentication in 1.0.12. Users dont need to hookup `displayCall` method for this to work.
