### ISSUE TITLE
AADSTS16000: Session is invalid due to expiration or recent password change.

### ISSUE THREAD

**Issue by gorlanrelayhealth** [AzureAD/azure-activedirectory-library-for-js#183]
When you reset the password of an Azure Active Directory user through the Azure management portal (not through the "Forgot password" flow), that user will be prompted to set a new password given their temporary password.

After you change it and log in, you are redirected to the authenticated page of the website using ADAL, but you can't make any service calls. Anything on the page will "load" indefinitely. If you try to click on something to make another call, you will get in the console: 

"AADSTS16000: Session is invalid due to expiration or recent password change.
Trace ID: 530e0295-1b76-4cee-a775-1404bb191a8a
Correlation ID: a06cff96-75ee-4775-8a71-81828e641af2"

Logging out and logging back in will allow you to make calls again.

**Comment by lukianol** [comment]
We face the same issue

**Comment by weijjia** [comment]
After you change it and login, how do you trigger the login? only look into the cache?

**Comment by gorlanrelayhealth** [comment]
The login is triggered through Adal's authentication service when a user clicks on a link. We use the login() method which is located in an AngularJS directive.

**Comment by sfgadjo** [comment]
@weijjia Any status on this issue?

**Comment by weijjia** [comment]
When you receive the error "invalid session due to expiration or recent password change", you should trigger another interactive login through sign in. We cannot do the auto-renew in the lib itself for now, this requires user to sign-in again. In the future, we plan to provide a pop-up, and when this kind of error is returned, and if the pop-up is opt-in, we'll launch a pop-up to achieve this.

**Comment by sfgadjo** [comment]
Thanks for the status update @weijjia. Do you have a recommendation for intercepting this error? Can we use one of the events adal.js publishes?

**Comment by tushargupta51** [comment]
The indefinite load has been fixed in 1.0.10. When adal gets this error as a result of renewing the token, the registered callback is called with the error description. App needs to trigger a login to fix this issue since the password has been changed. Closing this, please let us know if you still run into issue, will reopen it.
