### ISSUE TITLE
Expired Token Doesn't Refresh in iframe successfully

### ISSUE THREAD

**Issue by zachcarroll** [AzureAD/azure-activedirectory-library-for-js#190]
it seems that once a token is expired, my UI, which is particularly state-heavy, and thus can't be solved with a browser refresh, API calls don't even get sent out, they just error out with a status code of -1

**Comment by fhellwig** [comment]
I too had a similar issue. I believe the culprit is the `isEndpoint` check on line 282 in `adal-angular.js` v1.0.7.

Only if `isEndpoint` is set to `true` in this loop will the code starting at line 295 be executed. (Of course, this is predicated on the original token having expired as checked on line 275.)

The fix was adding the URI base for our own (non CORS) API calls into the `endpoints` array. In our code, this URI base is `/api`. Adding this key with the app's client ID resolved the refresh issue.

My approach is a workaround and a better long-term fix is most likely possible.

**Comment by tushargupta51** [comment]
this has been fixed in 2895778dbe1b399ee47f5338786592728a975bfb. Will be available in next release: 1.0.9.
