### ISSUE TITLE
Removal of token hash in html5 mode causes a browser refresh

### ISSUE THREAD

**Issue by Hagsten** [AzureAD/azure-activedirectory-library-for-js#201]
When adal-angular.js tries to remove the token hash (#id_token...) in html5 mode the browser (Chrome) performs a refresh. This is not (i guess) the intended behaviour, it should just remove the hash without a refresh. Below is the code that causes this:

```javascript
if ($location.$$html5) {
   $window.location = $window.location.origin + $window.location.pathname;
} else {
    $window.location.hash = '';
}
```

The browser will refresh when location is set without hash, for example setting location to http://mywebsite.com/foo will issue a refresh while http://mywebsite.com/foo# wont.

A suggestion is to use the $location.hash() instead. This will remove the hash when an empty string is sent in, it will keep the hash (# char) however. This should be the intended behaviour.

```javascript
if ($location.$$html5) {
    $location.hash('');
}
```

or perhaps using url and setting origin, path and search but omitting the hash?

```javascript
if ($location.$$html5) {
    $location.url($window.location.origin + $window.location.pathname + $window.location.search);
}
```

**Comment by mbrand** [comment]
I was about to ask the same question, since we're having problems with it, too.
I'm really wondering why you're doing a full page reload with 
```
$window.location = $window.location.origin + $window.location.pathname;
```
when you're in html5-mode, while you won't do a full page reload when your not
```
$window.location.hash = ''; // this doesn't do a reload.
```

**Comment by katagaStyle** [comment]
I was fighting this issue today, too. :(

**Comment by katagaStyle** [comment]
Any news about bug fixing from microsoft? Pretty annoying bug. :(

**Comment by jonaseriksson84** [comment]
I am not in html5 mode, however my application (which resides in a Sharepoint page) issues refreshes because of the `$window.location.hash = '';` line, causing me to lose the Office navbar. 

A workable solution I've found so far is to replace this line with Hagstens `$location.hash('');`, which seems to do the trick with no unnecessary pageloads.

**Comment by elferone** [comment]
This line of code: 
`$window.location = $window.location.origin + $window.location.pathname;`
was causing a refresh in my Angular application, which most of the time screwed up my angular ui router because of the refresh.

Changing to this:
`$location.url($window.location.origin + $window.location.pathname + $window.location.search);`
totally solve my problem.

**Comment by tushargupta51** [comment]
We updated our code to use `$location.hash()` to reset the hash and also use event.PreventDefault to prevent a location change when renewing the token in iframe. That should fix this issue.
