### ISSUE TITLE
domain_hint in extraQueryParameters produces invalid URL for renewToken

### ISSUE THREAD

**Issue by mrsmitty** [AzureAD/azure-activedirectory-library-for-js#204]
when adal init is configure with
`extraQueryParameters: 'domain_hint=mydomain.com'`

`_renewToken` calls `urlNavigate += '&domain_hint=' + encodeURIComponent(this._getDomainHint());` however, the previous call `this._getNavigateUrl('token', resource)` also includes the domain_hint from the serialized `this.config`.

This causes duplicate domain hints to be entered into the url and authentication fails.

`_renewToken` and `_renewIdToken` should check if the user has provided a domain hint and not re-add it to the navigation url.

**Comment by wakurth** [comment]
I had this same exact issue, and fixed it via pull request a while back. https://github.com/AzureAD/azure-activedirectory-library-for-js/pull/171

have you updated the version of your library since that point?

the function here:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal.js#L342

was added to check duplicate query string parameters

**Comment by mrsmitty** [comment]
I've looked at 1.0.7 and can see this issue has been resolved. Closing, thanks.
