### ISSUE TITLE
Renew token issue

### ISSUE THREAD

**Issue by bveerendrakumar** [AzureAD/azure-activedirectory-library-for-js#206]
We are facing a strange issue and that too its happening only in IE,. It is AADSTS65001: No permission to access user information is configured for 'clientid' application, or it is expired or revoked.. I really did not understand why this issue is coming during renew token. If permission is not there it should fail during login itself. Can anybody help us on this?

**Comment by bveerendrakumar** [comment]
We checked AAD permissions and all of them are properly set to read users information. It actually works when we clear the cache and relogin or open a private session. Any guidance or help on this is much appreciated

**Comment by weijjia** [comment]
it only happens on IE? did you try with some other browsers, i.e. chrome?

**Comment by tushargupta51** [comment]
@bveerendrakumar are you still hitting this issue? Have you tried other browsers?

**Comment by tushargupta51** [comment]
Dup of #101 

It is failing probably because client does not have the required permission to access the web api, it won't fail during login since that process does not include accessing a web api.

Have you followed the instructions here: https://github.com/AzureADSamples/SinglePageApp-WebAPI-AngularJS-DotNet, updating manifest and checking right permissions in azure portal?

**Comment by tushargupta51** [comment]
Closing this as dup. Please follow #101 for resolution/progress.
