### ISSUE TITLE
Refresh token infinite loop.

### ISSUE THREAD

**Issue by estene** [AzureAD/azure-activedirectory-library-for-js#216]
Hi! I am having a similar problem as to some other issues, though not exactly the same. Running 1.0.7

When the adal.expiraration.key expires it attempts to refresh the token. When this happens we are caught in an infinite loop. The only error I can see is : "Nonce is not same as ..." and it constantly changes these values.

Attempting to clearCache() and calling signIn() after seems to work around this issue. Any idea what might be wrong?

**Comment by jtaubensee** [comment]
I'm currently experiencing the same issue. I had a stackoverflow post about it here: http://stackoverflow.com/questions/34686460/adal-js-nonce-is-not-same-as-undefined/34687262?noredirect=1#comment57302402_34687262

**Comment by weijjia** [comment]
I'm investigating a similar issue. Can you send me the fiddler trace along with adal logs? This will definitely help.

**Comment by atkinchris** [comment]
I've been experiencing the same symptom of infinite loops; however, in my case I'm using an altered fork to work with `require` and webpack - as such, there could be a different root cause, but the information might be useful.

The issue I was encountering was where the callbacks in the iframes created to grab tokens, tried to access `window.parent.AuthenticationContext`. However, as this had not been made available on the global scope (thanks to webpack's scope protection for modules), it didn't exist. This caused the renew callback to fail - and another to be issued - and an infinite loop began.

https://github.com/atkinchris/azure-activedirectory-library-for-js/commit/6b10d54a718c7d8cf04d8cf94ffaa328a91608d4

**Comment by ssmock** [comment]
When I encountered this issue, I discovered that even though `this._supportsSessionStorage()` returned `true`, sessionStorage wasn't actually working.  Edge was my browser.

The "workaround:" make the site trusted in my browser.  (Quotes for emphasis -- this is barely a workaround.)

**Comment by tushargupta51** [comment]
That happens when there is a mismatch between the nonce sent back from azure ad and the one in the cache. Whenever you call AuthenticationContext.login(), it resets the nonce in the cache.

Can you capture logs at verbose level (Logging.level = 3) or even better attach a fiddler trace? That would help diagnose the issue better.

**Comment by estene** [comment]
@tushargupta51 I have attached a copy of a log with logging.level = 3. 
Sorry for the late reply!

[adallog.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/206091/adallog.txt)

**Comment by gabbsmo** [comment]
#202 is a similar issue. I've posted more details there.

**Comment by tushargupta51** [comment]
@estene @gabbsmo can you try 1.0.10 and see if you still encounter this issue? Thanks!

**Comment by estene** [comment]
@tushargupta51 Is the anonymousEndpoints now required in the adalOptions? By not doing any changes but updating the library I am getting an Cannot read property 'push' of undefined here: 
`if (toState.templateUrl && !isAnonymousEndpoint(toState.templateUrl)) {
                                _adal.config.anonymousEndpoints.push(toState.templateUrl);
                            }`

**Comment by PavelPikat** [comment]
I run into the same issue. Fixed it by having  anonymousEndpoints: [] in my  adalAuthenticationServiceProvider.init

**Comment by thibnes** [comment]
Hello, 
after declaring anonymousEndPoints: [] in my adalAuthenticationServiceProvider.init I got this:

```
Navigated to https://localhost:44300/
routes.config.js:293 Tue, 10 May 2016 08:05:15 GMT:d8f93f57-3d8c-4b36-90b3-15a39f2cfd44-1.0.10-VERBOSE: Url: Content/i18n/fr_FR.json maps to resource: 581ccc28-fa8d-4aca-8cba-9b142887a9f2
routes.config.js:293 Tue, 10 May 2016 08:05:15 GMT:d8f93f57-3d8c-4b36-90b3-15a39f2cfd44-1.0.10-WARNING: User login is required
routes.config.js:293 Tue, 10 May 2016 08:05:15 GMT:d8f93f57-3d8c-4b36-90b3-15a39f2cfd44-1.0.10-ERROR: Error when acquiring token for resource: 581ccc28-fa8d-4aca-8cba-9b142887a9f2
stack:
undefined
```

Works fine with 1.0.8.

Here is my config:

```
var endpoints = {
			"api/v1": myClientId,
			"https://graph.microsoft.com": "https://graph.microsoft.com"
		};

		adalProvider.init(
		{
            anonymousEndpoints: [],
			instance: 'https://login.microsoftonline.com/',
			tenant: myTenantId,
			clientId: myClientId,
			endpoints: endpoints,
			cacheLocation: 'localStorage'
		},
		$httpProvider
		);
```

**Comment by tushargupta51** [comment]
@estene @PavelPikat No, anonymousEndpoints need not to be initialized. This is a bug. Opened #282 to track this. Adding anonymousEndpoints: [] should remove that error.

@thibnes can you share your routeProvider config?

**Comment by thibnes** [comment]
@tushargupta51 here we go:

```
(function () {
	'use strict';

	angular
		.module('app.routes')
		.config(routesConfig);

	routesConfig.$inject = ['$stateProvider', '$locationProvider', '$urlRouterProvider', 'RouteHelpersProvider', '$httpProvider', 'adalAuthenticationServiceProvider'];
	function routesConfig($stateProvider, $locationProvider, $urlRouterProvider, helper, $httpProvider, adalProvider) {

		$locationProvider.html5Mode(false);

		// default view
		$urlRouterProvider.otherwise('/SingleView');

		// 
		// Application Routes
		// -----------------------------------   
		$stateProvider
		.state('app', {
			//url: '/',
			abstract: true,
			resolve: helper.resolveFor('modernizr', 'icons'),
			views: {
				  'content': {
					  template: '<div data-ui-view="" autoscroll="false" class="content-wrapper"></div>'
				  }
			  }
		})
		.state('app.singleview', {
			url: '/SingleView',
			title: 'Single View',
			templateUrl: helper.basepath('SingleView/Index')
		})
.state('app.candidatesView', {
			url: '/Candidates',
			title: 'Candidates View',
			controller: 'RecruitmentCandidatesController',
			controllerAs: 'vm',
			requireADLogin: true,
			templateUrl: helper.basepath('Recruitment/Candidates')
		});

} // routesConfig

var endpoints = {
            "api/v1": myClientId,
            "https://graph.microsoft.com": "https://graph.microsoft.com"
        };

        adalProvider.init(
        {
            anonymousEndpoints: [],
            instance: 'https://login.microsoftonline.com/',
            tenant: myTenantId,
            clientId: myClientId,
            endpoints: endpoints,
            cacheLocation: 'localStorage'
        },
        $httpProvider
        );

})();
```

**Comment by tushargupta51** [comment]
@thibnes By default, adal ignores url (templateUrl) for states/routes that do not require authentication, e.g. `templateUrl: helper.basepath('SingleView/Index')` in your example. For all other relative urls (App's backend urls), it requires an authenticated user unless that uri (or a superset of that uri) is listed in `config.anonynousEndpoints`. For example, if you have files under /Content/i18n or /Content, then you can add `anonymousEndpoints=[ "/Content" ]` or `anonymousEndpoints=[ "/Content/i18n" ]` depending on how generic you want it.

**Comment by thibnes** [comment]
@tushargupta51 I understand, however it seems that adding `anonymousEndpoints=[ "/Content" ]` for instance has no effect.

I still got the login required warning upon my /Content/ url.

```
Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-VERBOSE: Url: Content/i18n/fr_FR.json maps to resource: 581ccc28-fa8d-4aca-8cba-9b142887a9f2
routes.config.js:293 Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-WARNING: User login is required
routes.config.js:293 Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-ERROR: Error when acquiring token for resource: 581ccc28-fa8d-4aca-8cba-9b142887a9f2
stack:
undefined
routes.config.js:293 Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-INFO: Getting error in the response
routes.config.js:293 Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-VERBOSE: Url: /Partials/TopNavbar maps to resource: 581ccc28-fa8d-4aca-8cba-9b142887a9f2
routes.config.js:293 Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-WARNING: User login is required
routes.config.js:293 Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-ERROR: Error when acquiring token for resource: 581ccc28-fa8d-4aca-8cba-9b142887a9f2
stack:
undefined
```

Besides, I missed to show you one line at the end in the log that is weird:
```
Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-VERBOSE: Url: /SingleView/Index maps to resource: null
4routes.config.js:293 Tue, 10 May 2016 08:50:48 GMT:668cc612-9617-4719-a175-3cc29d6215b7-1.0.10-INFO: Getting error in the response
```

Thank you for your help.

**Comment by estene** [comment]
I can confirm that adding anonymousEndpoints removed the error. 

As @thibnes I seem to experience some issues, I have a protected route to 'parent.dashboard', but this gets loaded even though I am not logged in/authed.
If I add say 'app/shell.html' to anonymousEndpoints or simply have `template: '<div ui-view></div>',` I get these errors:

```
Tue, 10 May 2016 09:10:25 GMT:aea6e183-f9f6-43ac-a25e-78b557af184d-1.0.10-VERBOSE: Url: app/shell.html maps to resource: null
Tue, 10 May 2016 09:10:25 GMT:aea6e183-f9f6-43ac-a25e-78b557af184d-1.0.10-VERBOSE: Url: app/dashboard.html maps to resource: null
```

Sample of my simple setup:
```
{
                state: "parent",
                config: {
                    abstract: true,
                    template: '<div ui-view></div>'
                }
            },
            {
                state: "parent.dashboard",
                requireADLogin: true,
                url: '',
                config: {
                    templateUrl: "app/dashboard.html"
                }
            }
```

**Comment by thibnes** [comment]
@estene I've seen you had the same issue as me, did you solved it?

**Comment by estene** [comment]
I thought initially I had the same issue, but I had some errors in my config which resolved the issue. 
In my case we had html5 mode enabled and azure iis rewrites, and I had the urls defined in the wrong section. 
Things seem to be working okay now. Need to do some more testing though.

**Comment by thibnes** [comment]
I managed to make it work. I added all the missing anonymousEndpoints going step by step in debug mode. The thing is that I have a bunch of inline templates with random names that I had to add too.

In my case, I have only one backend endpoint which is secured : 
```
var endpoints = {
			"api/v1": window.agiBusiness.appSettings.clientId,
			"https://graph.microsoft.com": "https://graph.microsoft.com"
		};
```

So all calls other than "api/v1/..." should be concidered as anonymous.

Did I miss something here?

**Comment by tushargupta51** [comment]
@thibnes Try using `anonymousEndpoints = [ "Content/" ]`. You can add a high level/root level uri to anonymous endpoints that will ignore all the children urls. If you do so, you don't need to add "api/v1" in `endpoints` unless you have something in `anonymousEndpoints` that will make adal to consider "api/v1" as anonymous also, e.g. "api" or "v1".

**Comment by Mansyn** [comment]
@atkinchris I think I'm having the same problem with my webpack setup and using adal. I haven't been able to figure out how to expose the Authenticationconext like you mentioned. Do you do that in your webpack.config or where exactly? Does is work with the 1.0.10 version?

**Comment by tushargupta51** [comment]
@Mansyn Can you expand on why and where you want to expose AuthenticationContext? Are you using angular? Are you running into an infinite loop?

**Comment by atkinchris** [comment]
@tushargupta51 When importing this library as a module, Webpack (and similar tools) protect the global scope from exports, to prevent collisions and leaks. This library requires `AuthenticationContext` to be exported to allow iframe callbacks to access it - so we need to tell Webpack explicitly to allow it to be exported.

@Mansyn I modified the library to use `require` instead of using `AuthenticationContext` from the global. The changes can be seen here https://github.com/atkinchris/azure-activedirectory-library-for-js/commit/6b10d54a718c7d8cf04d8cf94ffaa328a91608d4

The exporting was done by this line:

```javascript
var AuthenticationContext = require('expose?AuthenticationContext!./adal.js');
```

Note, this was with the version of the library as of my original comment; you'd probably want to fork a current version to add `require` support.

**Comment by Mansyn** [comment]
Thank you for getting back to me, this is the only issue holding up our
portal from going live and I'm still learning how to configure webpack.
When I tried to use a version of the module with your require statement in
it, I get an error about it not recognizing the require. Is there something
I need to change to add support for require in the module?

**Comment by tushargupta51** [comment]
Closing this issue, please let me know if anyone still hits the refresh token infinite loop.

@Mansyn @atkinchris Can you guys take a look at #262 and #223 , you might be hitting the same issue. If not, please open a new issue on this.

**Comment by spzSource** [comment]
@tushargupta51 
I have found another case, which is causes infinite looping for token refresh.
When we change local time to 3 or more hour ahead, iframe retrieves a new token, which is already expired in point of view our local time.

I don't think this is a frequent case... But it would be great to handle such situation: throw an error and break the loop for token refresh.

What do you think?

**Comment by tushargupta51** [comment]
@spzSource What I expect to happen in this case is that adal will still save the token, as it does not check the expiration at the time of saving the token in the cache. But later when token is requested, adal will find that it is expired and thus try to renew again (which will again get an expired token from point of view of local time). The only case where it will go into a loop, is when the token is requested again and again, making adal renew it every time. I don't think it will go into a loop when renewing the token. Let me know if that's not what's happening. Console logs will help debug this further.

Also, I think this is a discrepancy on client's end as the clocks are supposed to match.

**Comment by FredDale44** [comment]
I had the same issue of infite loop, with this error message "ADAL error occurred: User login is required".
The problem was the version of JQuery and Angular.
Worked for me use JQuery 1.5.6 and AngularJS 3.1.1.

Hope it help!

**Comment by richarjain** [comment]
I am facing same issue. Adal Infinite redirection in Edge. Can anybody help me out in this

**Comment by kurifodo** [comment]
I'm encountering the infinite loop with adal.js 1.0.14 and **I'm not using angular**. I've read this whole post, but cannot find a solution. I would like to avoid clearing cache before invoking login like others have mentioned doing.

**Repro steps:**
1. Visit my SPA in Incognito Mode to ensure clean state
2. Create authentication context and invoke handleWindowCallback()
3. Site prompts me to login since getCachedToken(myClientId) is null
4. Redirected to AAD login
5. Redirected back to site
6. Create authentication context and invoke handleWindowCallback()
7. Logged in successfully, all is well...
8. Wait for the id_token to expire (i was simulating this by setting the time to 0 in localStorage)
9. Refresh the SPA via browser's refresh button
10. Create authentication context and invoke handleWindowCallback()
11. Site prompts me to login since getCachedToken(myClientId) is null
12. Redirected to AAD login
13. Redirected back to site
14. Steps 10-13 repeat infinitely from here on

With the debugger stepping through handleWindowCallback(), I see adal.login.error gets set to "**Nonce is not same as undefined**" within saveTokenFromHash

**I enabled verbose logging, and here's what is present in the console at step 11:**
authenticator.js:26 Fri, 21 Jul 2017 05:37:50 GMT:1.0.14-VERBOSE: State: 84c5d552-3f24-4f7f-a871-71e67f8d6482
authenticator.js:26 Fri, 21 Jul 2017 05:37:50 GMT:1.0.14-INFO: Returned from redirect url
authenticator.js:26 Fri, 21 Jul 2017 05:37:51 GMT:1.0.14-INFO: State status:true; Request type:LOGIN
authenticator.js:26 Fri, 21 Jul 2017 05:37:51 GMT:1.0.14-INFO: State is right
authenticator.js:26 Fri, 21 Jul 2017 05:37:51 GMT:1.0.14-INFO: Fragment has id token

**adal config for my application:**
{
    cacheLocation: 'localStorage',
    clientId: '<my applicationId>',
    instance: 'https://login.microsoftonline.com/',
    postLogoutRedirectUri: window.location.origin,
    tenant: 'microsoft.onmicrosoft.com'
};

**Comment by vinodbobade** [comment]
Hello, I am having the same issue, after token expiry when it tries to refresh the token getting an error:Nonce received: XXXXX is not same as requested: YYYYY, please help.

**Comment by scott-lin** [comment]
@vinodbobade, I haven't looked at this in 3.5 years, but I dug up how I worked around it. Please see the discussion on Stack Overflow (https://stackoverflow.com/questions/45232064/infinite-login-loop-when-using-adal-js-1-0-14).
