### ISSUE TITLE
Handle AAD errors on callback

### ISSUE THREAD

**Issue by PavelPikat** [AzureAD/azure-activedirectory-library-for-js#254]
Maybe I'm missing something here, but I'm unable to catch errors returned by AAD on callback.

For example when the user refuses to consent and clicks 'Cancel' on login.microsoftonline.com, AAD redirects to %redirect_uri%/error=access_denied&error_description=AADSTS65004:+The+resource+owner+or+authorization+server+denied+the+request

adal-angular.js removes the query string by clearing $window.location.hash in locationChangeHandler and the error is not handled.

The error description get stored by adal.js in sessionStorage (or whatever storage type is used) as "adal.failed.renew" and "adal.error.description". 
However, "adal.login.error" is undefined and it's the only error adal-angular is referencing through userInfo.loginError

**Comment by tushargupta51** [comment]
@PavelPikat This is a login request,right? If an error is returned in the login response, don't you get a 'adal:loginFailure' broadcast?

**Comment by PavelPikat** [comment]
@tushargupta51 The user is already logged in (with user consent) and all tokens are in place. The app redirects the user to ask for admin consent. But then the user clicks 'Cancel'

I looked into adal-angular.js and found out that adal:loginFailure event is raised when one of the following conditions are met:
1. requestInfo.stateMatch is false
or 
2. _adal.isCallback(hash) is false

In my scenario, AAD redirects back to my app via callback, so adal:loginFailure is never broadcasted

**Comment by tushargupta51** [comment]
@PavelPikat Ok, so it seems its not a login request, its more like step-up authorization. In which case, the right behavior is to call the callback that was registered at the time of renewing the access token (in this case getting the access token with admin privilege). Why are you referring to user.loginError then?

**Comment by PavelPikat** [comment]
I don't think I'm following. 
I'm talking about a callback from login.microsoftonline.com/%tenant%/Consent/Deny. The callback contains some information about the error in the query string. Adal.js saves the error in its storage, but adal-angular.js doesn't provide any hooks to access captured error. 
I mentioned user.loginError because it's the only error accessible through adal-angular at the moment, and maybe the library should be extented so it is possible to access other error messages captured by adal.js, not only those on login.
![capture](https://cloud.githubusercontent.com/assets/3666748/14201872/f98aac1e-f7f4-11e5-8ee0-813bf7f00cbb.PNG)

**Comment by tushargupta51** [comment]
@PavelPikat 
> "The user is already logged in (with user consent) and all tokens are in place. The app redirects the user to ask for admin consent"
Is the redirect to ask for admin consent a result of fetching an access_token for a resource (that requires more privilege) or is it a request the application initiated without adal playing a role in that (except that it goes through interceptor).

Can you share the values of requestInfo.stateMatch and requestInfo.requestType?

**Comment by PavelPikat** [comment]
I am using this code to prompt the user:
`var adal = new AuthenticationContext();
        adal.config.displayCall = function adminFlowDisplayCall(urlNavigate) {
            urlNavigate += '&prompt=admin_consent';
            adal.promptUser(urlNavigate);
        };
        adal.login();
        adal.config.displayCall = null;`

When the user is returned back to my app after clicking cancel, stateMatch is true and requestType is LOGIN

**Comment by tushargupta51** [comment]
@PavelPikat If the response url has error, stateMatch is true and requestType is login:
1. https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L82 will load the error and error desc in the requestInfo object.
2. https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L10: It goes inside this if block since state is matched.
3. Since callback is not a function (is this incorrect?), it will go https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L116 and since user is not authenticated, it will go to the else block https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L138 and broadcase `loginFailure` event.

Am I missing something in this flow?

**Comment by PavelPikat** [comment]
The user is authenticated. I am asking already logged in administrator user to give admin consent.
Therefore loginFailure event is not raised

**Comment by tushargupta51** [comment]
@PavelPikat Earlier, when there is an error from AAD, adal-angular was not calling the callback. I added this in 1.0.10: https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal-angular.js#L110. I think your scenario falls into this code path, and it will call the registered callback with the error. Does this solve your issue?

**Comment by arunkumaresan** [comment]
I am facing the same issue. I am using adal / adal-angular version 1.0.10

I have configured: adalAuthenticationService.config.redirectUri
Upon Accept / Cancel, the locationChangeHandler is called multiple times. This loads the app twice due to the following code, once with the has part that has admin_consent=true / error=access_denied&error_description=AADSTS65004:
if ($location.$$html5) {
                            $window.location = $window.location.origin + $window.location.pathname;
                        } else {
                            $window.location.hash = '';
                        }
The redirectUri is expected to be called only once. Adal for angular doesn't behave the same as the .net in this case. Your help is very much  appreciated

**Comment by tushargupta51** [comment]
@arunkumaresan We are aware of locationChangeHandler called twice when a location changes. #151 is the tracking issue.

**Comment by arunkumaresan** [comment]
thanks @tushargupta51  Are there any expected time to see this isse resolved in upcoming versions?

**Comment by tushargupta51** [comment]
@arunkumaresan We plan to release the next version in couple of weeks.

@PavelPikat I am closing this issue. Let me know if you still run into the same problem, I will re-open this for discussion.
