### ISSUE TITLE
Authentication Error on non-requireADLogin routes

### ISSUE THREAD

**Issue by Blackbaud-ScottVossen** [AzureAD/azure-activedirectory-library-for-js#266]
I have a fairly simple angular application using ui.router where I have a homepage which you don't have to be logged in to view, and other pages you need to be logged in to view:

        $urlRouterProvider.otherwise('/');

        $stateProvider
            .state('home', {
                url: '/',
                templateUrl: 'app/home/home.html',
                controller: 'homeController as ctrl'
            })

            .state('dashboard', {
                url: '/dashboard',
                requireADLogin: true,
                views: {
                    '' : {
                        templateUrl: 'app/dashboard/dashboard.html',
                        controller: 'dashboardController as ctrl'
                    },
                    'fundSummaryTile@dashboard': {
                        templateUrl: 'app/dashboard/fund-summary-tile.html',
                        controller: 'fundSummaryTileController as ctrl'
                    }
                }
            })

            .state('fund', {
                url: '/fund/:id',
                requireADLogin: true,
                views: {
                    '': {
                        controller: 'fundDetailController as ctrl',
                        templateUrl: 'app/fund/fund-detail.html'
                    }
                }
            });

This worked just fine in version 1.0.8, but with the update to 1.0.9, this is now throwing a **stateChangeError** during the transition. The error shows the correct toState, but results in a **"User login is required" error message**. 

I switched my version back to 1.0.8 and things were working perfectly again. If there's something new I need to do to get this working in 1.0.9, please let me know.

**Comment by JoshDavisMP** [comment]
Commit 2895778dbe1b399ee47f5338786592728a975bfb to fix #195 removed the check on endpoints so now **all** service requests require authentication.

**Comment by gpit2286** [comment]
Currently, there is the option to `requireADLogin: false` in the state config that does not seem to work either.  I see that fixes you made in #275 but I wonder if the anonymous endpoint solution is the way to go.  Does that mean that we will no longer be able to specify the `requireADLogin` option as it would be obsolete?

**Comment by Blackbaud-ScottVossen** [comment]
@JoshDavisMP, so the functionality that allows someone to have a homepage that doesn't require you to be logged in is being removed? I see #275 addresses anonymous endpoints, but this doesn't seem to allow me to have a user visit one of my pages without being authenticated.

If there's a new way to accomplish this, please fill me in or point me to the correct documentation!

Please don't remove my requireADLogin!

**Comment by JoshDavisMP** [comment]
@Blackbaud-ScottVossen, I'm not part of developing the project, just a user. I can't help you because I'm struggling with solving the same problem. Presumably you can have a homepage that doesn't require a login as long as it doesn't make any API calls (anonymous or otherwise), but I haven't specifically tested it. All I know is that it refuses to load even mock data being called locally. I refuse to accept having to run a completely different application for anonymous calls or to turn off ADAL for mock data calls. Whoever made this change didn't think through the repercussions.

**Comment by Blackbaud-ScottVossen** [comment]
Ahh, I'm sorry for the confusion there. Well, hopefully we can find a resolution!

**Comment by tushargupta51** [comment]
@gpit2286 @Blackbaud-ScottVossen @JoshDavisMP  `requireAdLogin` is used to protect routes and make sure that a user is authenticated before accessing a specific route. `requireAdLogin` is still there and the changes in #275 does not override its functionality.

Currently, all requests made to app's backend are secured and require an access token. Interceptor will try to attach a token to the outgoing request header. Though the problem with this is that the interceptor tries to attach tokens even for the local resources. For example, loading `/app/views/home.html` requires a token to be present.

`config.anonymousEndpoints` provides a way to users to plug in app's backend urls which they want to call anonymously, interceptor will skip these urls and wont try to find a token for them. For example, adding `app/views` to the list will make interceptor skip all these requests: `app/views`, `app/views/home.html`, `app/views/about.html`, etc.

I agree about the expectation that if a user configured a route to not require user authentication, loading the corresponding local data should not require authentication and there should be no need to set `config.anonymousEndpoints` for that to work. I am working on getting this fixed the best way possible.

**Comment by Blackbaud-ScottVossen** [comment]
@tushargupta51 Thanks for your reply. I believe what you're describing solves the issue @JoshDavisMP is talking about. However, the issue I created this bug for a little different. 

Basically, I have a page in my application which does NOT have the requireADLogin flag on it, but the AdalJs library is forcing me to log in before viewing the page.

**Comment by tushargupta51** [comment]
@Blackbaud-ScottVossen 

> but the AdalJs library is forcing me to log in before viewing the page.

I am assuming you are seeing "User login is required" message in your console. Or are you getting redirected to login page? If its former, its happening because of what I described above. For example, in your example code, you configured "home" route to not require authentication. I am guessing loading "app/home/home.html" is throwing the message "User login is required". And that is because, by default, interceptor tries to tokens for all the requests sent to relative urls.

**Comment by gpit2286** [comment]
I'm looking at the code and I'm trying to wrap my head around a couple of things.  
- Previously, the `requireADLogin` was being handled, correctly, in the state change handler. (https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/f7b78cc481e5c02731dab13d4a29400e38c58812/lib/adal-angular.js#L198) 
- What happened is that the default behavior of the location handler was changed, as noted by the fix @tushargupta51 published, to test all routes. However, the location handler does not check the state object for the `requireADLogin` property and shoves everything into the same block of code. (https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/f7b78cc481e5c02731dab13d4a29400e38c58812/lib/adal-angular.js#L147) 
- The problem is that the location state handler only provides the location to the function as expected. (https://docs.angularjs.org/api/ng/service/$location#$locationChangeStart) 

Credo, to resolve this issue, all of the authentication checks are going to be made in the state change handler and none in the location change handler.  The alternatives seem to be either an anonymous catch all as suggested above, or a global variable that hold the 'to State' information, which is messy and not optimal. 

If you're having this problem, stay on 1.0.8 until it gets resolved.

**Comment by JoshDavisMP** [comment]
>  And that is because, by default, interceptor tries to tokens for all the requests sent to relative urls

That means that if the only thing other than requireADLogin routes that I want to force authentication for is external APIs then I need to add pretty much everything on my local site to anonymousEndpoints. It seems to me that if it's this aggressive that instead of having `config.anonymousEndpoints` that you should just make `config.endpoints` required again and force the definition of which endpoints authentication is required for.

**Comment by tushargupta51** [comment]
@gpit2286 As you said, location change handler checks if the hash has token or error, if not then it checks if user is authenticated or not (https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/f7b78cc481e5c02731dab13d4a29400e38c58812/lib/adal-angular.js#L150), if not then it tries to renew token. state/route change handler looks into the `requireAdLogin` attribute.

@JoshDavisMP I am working on a fix so that interceptor ignores the routes that do not have `requireAdLogin` on them. But if the associated controller (controller linked with the route that does not require authentication) makes any api calls, then interceptor will try to attach token to the outgoing request. To make this more clear, if this is the sample configuration:

        $stateProvider
            .state('home', {
                url: '/',
                templateUrl: 'app/home/home.html',
                controller: 'homeController as ctrl'
            })

            .state('dashboard', {
                url: '/dashboard',
                requireADLogin: true,
                views: {
                    '' : {
                        templateUrl: 'app/dashboard/dashboard.html',
                        controller: 'dashboardController as ctrl'
                    },
                    'fundSummaryTile@dashboard': {
                        templateUrl: 'app/dashboard/fund-summary-tile.html',
                        controller: 'fundSummaryTileController as ctrl'
                    }
                }
            })

            .state('fund', {
                url: '/fund/:id',
                requireADLogin: true,
                views: {
                    '': {
                        controller: 'fundDetailController as ctrl',
                        templateUrl: 'app/fund/fund-detail.html'
                    }
                }
            });

Then interceptor will ignore 'app/home/home.html' but if homeController  makes any api calls (either to app's backend or external apis, interceptor will attach a token). Also, navigating to  'app/dashboard/dashboard.html', or 'app/fund/fund-detail.html' will require token.

Does that sound right?

**Comment by tushargupta51** [comment]
1.0.10 fixes this. You should be able to navigate to routes that do not require authentication without seeing the "User login is required" error. Please let me know, if you still see issues, I will reopen the issue.

**Comment by gpit2286** [comment]
I like what you did to handle this.  However, in my case it doesn't fix the problem.  Myself, as well as @Blackbaud-ScottVossen, using ui-router.  In this case, your catch on templateURL does not work as the template URL lives inside of a "views" object. https://github.com/AzureAD/azure-activedirectory-library-for-js/commit/b03dd624a1d2d07b363a2717e5058cfcf164c6c3#diff-b665dc52059979b6da33bbc0e25e23f5R237 

This insures that toState.templateURL is always false and therefore never gets added to the AnonEndpoint array. 

General debugging info... 

Console:
```
Thu, 12 May 2016 06:35:10 GMT:b68a6d27-8d49-4ea9-91b9-21aa1adfe357-1.0.10-VERBOSE: Url: partials/login.html maps to resource: e8e709d5-ce34-4a50-a34e-2c77b788c427
Thu, 12 May 2016 06:35:10 GMT:b68a6d27-8d49-4ea9-91b9-21aa1adfe357-1.0.10-WARNING: User login is required
Thu, 12 May 2016 06:35:10 GMT:b68a6d27-8d49-4ea9-91b9-21aa1adfe357-1.0.10-ERROR: Error when acquiring token for resource: e8e709d5-ce34-4a50-a34e-2c77b788c427
stack:
undefined
Thu, 12 May 2016 06:35:10 GMT:b68a6d27-8d49-4ea9-91b9-21aa1adfe357-1.0.10-INFO: Getting error in the response
```

State definition: 
```
$stateProvider
    .state('login', {
      url: '/',
      requireADLogin: false,
      views: {
        "mainContent": {
          templateUrl: 'partials/login.html',
          controller: 'loginCtrl'
        }
      }
    })
```

**Comment by murtazajafferji** [comment]
+1. 1.0.10 does not fix the issue for me. I am not using ui.router.

**Comment by tushargupta51** [comment]
@gpit2286 Thanks for reporting this. That fix wont work with the config that you have. I will open another issue to track that specifically. You can use `anonymousEndpoints` to fix this. Maybe add "partials/login.html" or just "partials" if other partial pages also do not require authentication

**Comment by tushargupta51** [comment]
@murtazajafferji What is the error that you are seeing? Can you share logs and your config?

**Comment by murtazajafferji** [comment]
@tushargupta51 I had a bug because the path to my templates was different in another environment, so I added both paths and that resolved the issue. Would it make sense to add another config option to ignore all templates (urls containing ".html")?
