### ISSUE TITLE
ver 1.0.9 breaks ngInclude

### ISSUE THREAD

**Issue by vtan31** [AzureAD/azure-activedirectory-library-for-js#268]
After starting a new project and updating all my script files... I've narrowed it down to adal.js causing the problem. A simple nginclude would no longer work.  It would just show a commented out...

`<!-- ngInclude: '/App/Layout/shell.html' -->`

I'm using adal.js ver 1.0.8 for now and it is working.

Thanks

**Comment by gabbsmo** [comment]
Does the issue only appear when you include templates over http and not from a pre genereated $templateCache.

**Comment by tushargupta51** [comment]
@vtan31 What are the repro steps for this? What is it that comments out the ngInclude line? I am not sure I understand the issue completely.

**Comment by tushargupta51** [comment]
Closing this issue for now. We need more info to investigate this. If you still running into this issue, please comment with the repro steps and any other details, we will re-open the issue.

**Comment by yoerlemans** [comment]
I run into the same issue
I joined a project with an existing setup, we use templateCache and adal, we first used 1.0.8 and when we upgraded to 1.0.10 ng include breaks
When ng-include tries to retrieve the template from the template cached it uses the httpService and when doing this, the adal interceptor fires, first I thought this was because of a change in angular and the use of the template cache but when reverting to adal 1.0.8 the problem disappeared.

I debugged the ngInclude directive for a moment and when trying to retrieve the template, the error callback runs with the message from the interceptor of adal "User login is required"

**Comment by tushargupta51** [comment]
@yoerlemans This is happening because you are trying to load some pages before user authentication. You can add those urls to `anonymousEndpoints: [ ]` array and that should fix the error. If you can share your router configuration and the path of html that is giving the error, I can help further.
