### ISSUE TITLE
Using adal.js with other front end frameworks (i.e. React)?

### ISSUE THREAD

**Issue by darrenparkinson** [AzureAD/azure-activedirectory-library-for-js#277]
Is it possible to use adal.js with other front end frameworks outside of Angular?

**Comment by tushargupta51** [comment]
Currently, we only provide out-of-the-box support for angular. At the moment, we do not plan to release any integrations with React or other front end framework. Though, I guess you might be able to utilize adal.js since its plain JS.

**Comment by darrenparkinson** [comment]
That is a terrible response.  Why is it that only Angular is supported?  How am I supposed to authenticate users with my react app?

**Comment by vijayakumarrg** [comment]
I found this blog post https://blog.mastykarz.nl/building-office-365-web-applications-react/ which uses adal.js with React and I tried the same in my app. It Works as expected.

**Comment by kbrimington** [comment]
This is an exceptionally poor response. For Microsoft to push us toward React to use Office UI Fabric, but then push us away from React to use Adal.js sends a very confusing message. Bad form.

We desire using Office UI Fabric for a variety of apps integrating with Office 365; however, the general lack of documentation, samples, and integration with your flagship authentication library makes this an astonishingly frustrating experience.

**Comment by tushargupta51** [comment]
@kbrimington We are sorry for the bad experience. We will get together with the Office team to understand how they plan to handle authentication. We will also have API docs soon for adal.js, that will help write wrappers for other frameworks on top of it. Unfortunately, we don't have any current plans to extend support for another framework yet.

**Comment by ralexand56** [comment]
WTH!? Is Microsoft an angular company now? Is this part of an agreement when the angular team signed on to use Typescript in angular? This is counter to MS's very open policy they have been demonstrating lately.

**Comment by danielrbradley** [comment]
I'm also trying to integrate a React app with adal, but have just come across the [hello.js library](https://github.com/MrSwitch/hello.js) which seems less tied to any specific framework. Has anyone tried this as a replacement? Is there anything it doesn't do that adal would?

**Comment by dancampbell691** [comment]
Has anyone, anywhere, figured out how to make AAD/adal.js work with anything other than Angular, like maybe Vue?  I've searched from one end of the internet to the other, and tried all 987 combinations of "examples" offered by Microsoft.  I've got dozens of hours into this effort, and the only thing I have to show for it is that my nearly-20 year devotion to Microsoft tools is becoming seriously suspect.  I've been frustrated before, but this is just asinine.  It's 2017.  Someone at MS should be able to demonstrate how to to get a Vue app to authenticate against an AAD-secured Web API.

**Comment by jmprieur** [comment]
It is possible to use ADAL.js with plain JavaScript (and hence with any framework). I'm writing a sample about this.

**Comment by dancampbell691** [comment]
Thank you, Jean-Marc!  I will anxiously await it.

**Comment by jmprieur** [comment]
@dancampbell691 : this is still work in progress, but you can look at the TodoListSPA in the additionalClaimsSupport branch of the active-directory-Dotnet-webapi-onbehalfof sample in GitHub: https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/tree/additionalClaimsSupport.

More to come

**Comment by dancampbell691** [comment]
@jmprieur: Thanks so much for this; and for turning it around so fast.  It was a huge help.  I was able to get it going and then was able to figure out the differences from what I already had going (with a Vue client and SSL Web API with CORS).

For everyone else trying to do this, the two key take aways which I had not been able to find elsewhere are these:
1.  In the manifest for your API, you must add the ClientId of your client App in the knownClientApplications, like this:
"knownClientApplications": [
    "4a22d9df-9800-4668-8289-a592d5160f9a"
  ],
(I actually remember seeing this on Stack Overflow, but it was old and not marked as an answer, and something contradictory was marked as an answer.)
2.  You need the 1.0.15 version of adal.js, which as far as I can tell is not yet the master.  (The version that is embedded in the example does not match master, but it is identical to the 1.0.15 branch, right down to still having 1.0.14 still listed in the code.)  Perhaps @jmprieur can clarify that?
3. FYI, I have the WebAPI running on SSL and using OWIN CORS, unlike in the example, so those are not requirements.

@jmprieur: a couple little hiccups in the example that I wanted to point out, since I hope you intend to fully publish it:
1. As I mentioned above, the issue with the version of adal.js
2. In the ReadMe, you might want to include a tip to watch for blocked pop-ups. The initial authentication popup seems to be allowed, but the second, for permissions, which only happens once, is disallowed, unless you tell Chrome to allow it.  Nothing in the debugger indicates that's what happened, so you get the impression that the whole thing has just died, until you finally notice that it's just the pop-up blocker.
3. Those scripts for creating and destroying the AAD stuff are awesome!  But I did notice one little quirk, which is certainly an outlier situation. On the primary subscription that I use, my email domain is different than the tenant domain, and the scripts used my email domain in all the places where it needed the tenant domain (even though my login domain is the tenant domain, strangely).

Thanks again for the fast and effective help!

**Comment by jmprieur** [comment]
@dancampbell691 : thanks for trying out the bits, and confirming that worked for you, and thanks for your feedback.
To answer your questions
1. We just released adal.js 1.0.15. It's now live. The sample was exercising it a few days in advance
2. I still need to work on the README for the sample (which I have not updated with the JavaScript sample yet)
3. In your particular case, I would recommend that you call the scripts with the long form, which is -TenantId <yourTenantId> and -Credentials <yourCredentials>. I did not have time to update the README yet about this aspect, but you can have a look at this one: [README.md for active-directory-Dotnet-daemon-certificate-crendential](https://github.com/Azure-Samples/active-directory-dotnet-daemon-certificate-credential)

```PowerShell
$secpasswd = ConvertTo-SecureString "<yourpassword>" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential (“automation@<yourtenant>.onmicrosoft.com”, $secpasswd)
. .\Cleanup.ps1 -Credential $mycreds -TenantId <yourTenantId>
. .\Configure.ps1 -Credential $mycreds -TenantId <yourTenantId>
```

**Comment by jmprieur** [comment]
@dancampbell691 : I've committed a new version of the sample in the same branch; https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/tree/additionalClaimsSupport. This version also demoes the redirect mode (login with redirect instead of popup, and acquireTokenRedirect instead of acquireTokenPopup). 
to toggle the behavior, just change the popUp member of config (in appconfig.js)

It also uses the user from the cache if it can. The experience is better.

**Comment by RehanSaeed** [comment]
I raised https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/659 to get this repo split into adal-angular and adal.js.

**Comment by salvoravida** [comment]
https://github.com/salvoravida/react-adal

**Comment by FDMatthias** [comment]
A bit late, but I've written a blogpost about this [here](https://www.appfoundry.be/blog/2018/11/24/authentication-with-adal-in-react-single-page-applications/) and put a sample of a React SPA with Adal on github [here](https://github.com/appfoundry/react-adal-authentication-session-sample/tree/Authentication-with-ADAL-in-React-SPA) (includes step by step commits and multiple branches).
