### ISSUE TITLE
Failed renewal against the common endpoint

### ISSUE THREAD

**Issue by abettadapur** [AzureAD/azure-activedirectory-library-for-js#287]
I am developing a multi-tenant application with ADAL.js, which means I am trying to authenticate against the 'common' endpoint.

This works fine for most cases, including initial login and token renewal.

However, in the edge case where I try to renew a token with an expired or missing AAD browser session, I do not receive a silent error in a callback url. Instead, the hidden iframe loads the AAD page  and gets stuck with the following error: 

**"AADSTS50059: No tenant-identifying information found in either the request or implied by any provided credentials."**

If I replace 'common' with my tenant id, I receive the appropriate silent error

This does not match the expected behavior of the 'prompt=none' query parameter.
Is this an AAD bug? Is there a workaround?

**Comment by tushargupta51** [comment]
@abettadapur Which version of ADAL are you using? Can you share logs (instructions are in readme)?

I assume aad is returning an error in the url as a fragment, adal should save that error in configured storage. Are you using adal-angular module or plain JS?

**Comment by abettadapur** [comment]
AAD is not returning an error in the url as a fragment when the common endpoint is specified, that is the issue. 
If I replace common with my tenant-id, I get back an error in the url fragment. Sorry I didn't make that clearer. 

I'm using the plain library and am on version 1.0.10

**Comment by tushargupta51** [comment]
@abettadapur Based on an internal discussion, AAD returns an error page instead of the error in url for "common" endpoint. Since its not in the url, adal cannot retrieve that error and save it in local storage or send it to callback. This is a question for AAD team, we already have an email thread on this though there is no response yet on this.

I am closing this for now as it seems to be an AAD behavior. If we later decide that a change needs to be made in adal, I will re-open this.
