### ISSUE TITLE
Forcing token renewal

### ISSUE THREAD

**Issue by sjaanus** [AzureAD/azure-activedirectory-library-for-js#290]
I have an issue that user leaves the web app open for too long and comes back and starts pushing buttons, which send out AJAX request that has the expired bearer token, thus getting bunch of error messages on screen.

The token is renewed only on route change or page refresh. Is it possible to force renewal of token in this case? Maybe using LoggingHttpInterceptor or similar?

**Comment by ischrei** [comment]
Hi,
Your question may describe 2 scenarios, depending on the AAD cookie state.
When the AAD cookie is valid (even when the user comes back after a long time), the ADAL JS's $http interceptor will refresh the access token if the URL should be protected.
The other scenario, when the AAD cookie is expired, requires a whole page refresh, to re-initiate login and renew the cookie. Without the login, AAD will return the following error "AADSTS50058: User account identifier is not provided...." which will be sent in the "adal:loginFailure" event.
The UX approach as I see it should be presenting an error message to the user, asking him to refresh the page and login again (or a better approach, similar to the Azure portal - disabling all the page, besides a 1 line with a message and a "Refresh" button.

**Comment by tushargupta51** [comment]
@sjaanus You can call `acquireToken` method to initiate the token renewal process. As @ischrei said, it will work only if aad cookie is valid. If the cookie is expired, then user will have to login again. Since adal token renewal process is silent, it does not redirect user to login page when it identifies a token renewal failure. It broadcasts events that app can capture and then redirect user to login page using `login` method.

**Comment by tushargupta51** [comment]
@sjaanus Does the above information help you address the original issue?

**Comment by ruisilva450** [comment]
I'm using AdalJS 1.0.8 (because 1.0.9 was causing problems with infinite loop creation of iframes with another angular app instantiation inside it causing a big mess) and I am using acquireToken inside a $interval of n minutes because I can't trust the automatic renewal (was causing problems with 401, again).
But even when I use acquireToken it operates in two ways depending of how much time is left until the token expires:
1. If the token is still valid we receive a response saying it had renewed the token (FALSE since it only checked if one is still valid instead of forcing the renewal)
2. If the token is NOT valid anymore, it makes the renewal and causing controllers to restart and brake the logic I had until then.

PS. If this behaviour is fixed in a more recent version, please let me know.

**Comment by tushargupta51** [comment]
@ruisilva450 I think you can take advantage of `config.expireOffsetSeconds` setting. Be default, it is 2 minutes which means, if a token is requested which is about to expire in 2 minutes, instead of returning the token, `getCachedToken` method returns null.

So, if you are using `acquireToken` method, it will first call the `getCachedToken` method to see if there is a token in the cache and if token is within that "expire offset" window, it renews the token, otherwise it serves the token from the cache.

So, you can set that expireOffsetSeconds to an interval of your choice. The default lifetime of access token is 1 hr. So, if you are forcing renewal every 45 minutes, you can set this offset to 15 minutes.

**Comment by tushargupta51** [comment]
Closing for now. Let me know if this is still an issue, I will re-open it.

**Comment by kajo1980** [comment]
Hi, we have a scenario where we want to make multiple calls (3 - 4) in succession to graph. i want to avoid a scenario where the token expires in between these calls. is there a way i can detect that the token is about to expire (based on the time i would need to complete all the calls) and renew it proactively? thanks.

**Comment by abhaygitty** [comment]
@tushargupta51 I am trying to renew the token with a custom expiration offset value from config.
But I don't think, that the acquireToken() method works as expected.
I meant, the expiration time of the token doesn't get updated after being reset to 0 in the getCachedToken()
` /**
     * Gets token for the specified resource from the cache.
     * @param {string}   resource A URI that identifies the resource for which the token is requested.
     * @returns {string} token if if it exists and not expired, otherwise null.
     */
    AuthenticationContext.prototype.getCachedToken = function (resource) {
        if (!this._hasResource(resource)) {
            return null;
        }

        var token = this._getItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource);
        var expiry = this._getItem(this.CONSTANTS.STORAGE.EXPIRATION_KEY + resource);

        // If expiration is within offset, it will force renew
        var offset = this.config.expireOffsetSeconds || 300;

        if (expiry && (expiry > this._now() + offset)) {
            return token;
        } else {
            this._saveItem(this.CONSTANTS.STORAGE.ACCESS_TOKEN_KEY + resource, '');
            this._saveItem(this.CONSTANTS.STORAGE.EXPIRATION_KEY + resource, 0);
            return null;
        }
    };`

Further the renewIdToken() function is called due to the null token returned from the getCachedToken() function.
![image](https://user-images.githubusercontent.com/22489833/57414636-8e802b00-71be-11e9-8c45-c75e20e64a68.png)

Here in the above function, the RENEW_STATUS doesn't change to complete.
Therefore, I tried invoking the handleWindowCallBack() funtion (within which there's a call to the saveTokenFromHash() function which writes the token and the expiration Epochs to the sessionStorage and also does switch the status from "In progress" to "Completed" as seen below) which again fails to run as the window.location.hash is empty.

![image](https://user-images.githubusercontent.com/22489833/57414979-fdaa4f00-71bf-11e9-9189-4519a1577549.png)

In addition to the above problem, I would also like to know, "when does the window.location.hash field get its value written?"

Please do guide me on what's wrong with what I am doing. 
Thanks in advance.
