### ISSUE TITLE
Token expire causes broken interceptor

### ISSUE THREAD

**Issue by katagaStyle** [AzureAD/azure-activedirectory-library-for-js#291]
We have some token expire issues. When local storage is empty then everything works fine. After some time we get in trouble when we reuse the application. 

We can reproduce this behaviour when setting expire token in local storage to expired (e.g. 0). This causes that broken interceptor is thrown and we end up in an endloss refresh loop. 

Same behavior in release1.0.11 branch. :(

**Comment by tushargupta51** [comment]
@katagaStyle Can you please share console logs for the refresh loop?
Logging = {
    level: 3,
    log: function (message) {
        console.log(message);
    }
};

You might need to turn on debug mode to capture logs otherwise browser might hang because of endless loop. Which browser have you tried this on?

**Comment by katagaStyle** [comment]
Hi. 

I set expire of both entries in local storage to 1 (simulate default expire...). After this i did a full page reload and end up in endless reloads. 

[adal_log_level_3.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/313974/adal_log_level_3.txt)

**Comment by tushargupta51** [comment]
@katagaStyle Can you try using the scripts in dev branch? One of the errors in the log is related to "config" object not returned in rejection, which we fixed in dev branch. Also, we have handled some of the commonly occurring infinite loop issues there.

**Comment by tushargupta51** [comment]
@katagaStyle Did you get a chance to try the bits in "dev" branch? Let me know if this is still and issue.

**Comment by tushargupta51** [comment]
Let us know when you have more info. I will reopen the issue for discussion. Thanks.

**Comment by gabbsmo** [comment]
I also have this issue. If I sign in to my app and then set the key "adal.access.token.key{guid}" to 0 in localStorage and refresh the next $http request fails with status 401. localStorage.clear() and it works again. Running the 1.0.11 release.

**Comment by tushargupta51** [comment]
@gabbsmo Can you share some logs?

**Comment by rohitnarula7176** [comment]
@gabbsmo In order to test the expired access_token behavior, you should either delete the particular entry from the cache or remove its value from the cache. In your test, you are setting the value to 0 which is still a valid entry but an invalid value for the access token. By doing so, you are prepending "Bearer 0"('Bearer ' + token) to the request for the resource which has an invalid token and hence you receive a "401" (Unauthorized). 
I have tested this with version 1.0.10 and 1.0.11 and the token is renewed as expected on page reload if you follow the above mentioned steps.
