### ISSUE TITLE
Redirected to pre-signin URL after user logs out

### ISSUE THREAD

**Issue by drGarbinsky** [AzureAD/azure-activedirectory-library-for-js#361]
We started seeing a new issue with the logout -> log back user flow. The steps are as follows

1: log into app
2: get redirected to AD
3: log in and get redirected back to app
4: logout
5: get redirected to AD
6: get redirected to app post log out url( https://someHost/#/signout )
7: click login on the "you've been sing out" page
8: get redirected to AD
9: **login and get redirected back to the post out URL location**

Using 1.0.11

The expected behavior is that the user is always redirected to the root of the app. I've tried setting redirectUri to the app root URL in the config but this has had no impact.

**Comment by tushargupta51** [comment]
@drGarbinsky Adal always saves the start page when logging in the user. Start page is the location from where the login process has started. Once login is completed, adal redirects the user back to the start page. This was broken prior to 1.0.11. There are use cases where always redirecting the user back to root page after login is not the right behavior. For example, if user starts with a url that requires authentication: `https://www.example.com/#/department/1?key=value`. After login, user should be redirected back to original url instead of `https://www.example.com`

But, I understand that your scenario is also a valid one. We have a community PR ( #337 ) to make this behavior of 'always redirecting the user to start page' customizable (thanks to @spzSource). I will look into this issue (and the PR) and investigate into what's the best way to handle this.

**Comment by drGarbinsky** [comment]
Thanks for the quick reply.

That behavior  makes sense now. I was able to detect that the user is signing in and on the signed-out landing page. Then redirect to the root. 
Closing
