### ISSUE TITLE
RedirectUri not working in 1.0.11

### ISSUE THREAD

**Issue by alan994** [AzureAD/azure-activedirectory-library-for-js#371]
Hi,

    We have a serious problem with url redirect after AAD login. The situation is following.

    I have a welcome page "localhost:port/" (state welcome, not require ADLogin) that displays the LOGIN button.
    Login button redirects with state.go("home") to url "localhost:port/#/home". This state requires authentication (requireADLogin: true).
    When I click on LOGIN, ADAL fires up and redirects to Microsoft AAD login page. I enter my credentials there and click login then ADAL redirect me to
    welcome page instead of home.

   ```
 //WELCOME STATE
   
 .state('welcome', {
        url: '/',
        templateUrl: 'app/welcome/welcome.html',
        controller: 'Welcome',
        controllerAs: 'vm'
    })

    //BASE STATE - in my opinion not important 
    .state('base', {
        abstract: true,
        templateUrl: 'app/blocks/router/base.html',
        onEnter: ['tenantDataService', '$sessionStorage', '$state', 'logger', '$rootScope', function (tenantDataService, $sessionStorage, $state, logger, $rootScope) {
            if (!$sessionStorage.tenantInfo && !$sessionStorage.tenantIsNotDefined && $rootScope.userInfo.isAuthenticated === true) {
                tenantDataService.getTenantInfo().then(function (data) {
                $sessionStorage.tenantInfo = data;
            }, function () {
                //logger.info("Failed to fetch tenant info");
            });
            }
        }]
    })

    //HOME STATE
    .state('home', {
        parent: 'base',
        requireADLogin: true,
        url: '/home',
        templateUrl: 'app/home/home.html',
        controller: 'Home',
        controllerAs: 'vm'
    })

    


    //ADAL CONFIGURATION
    adalAuthenticationServiceProvider.init({
        clientId: 'my client id',        
        redirectUri : 'http://localhost:6244/#/home', // Not working with or without this
        endpoints: {
        'https://graph.microsoft.com': 'https://graph.microsoft.com',
        'http://localhost:6244': 'http://localhost:6244'
        },
        cacheLocation: 'localStorage',
        extraQueryParameter: 'nux=1'
    }, $httpProvider);
```

**Comment by tushargupta51** [comment]
@alan994 It's happening because adal saves the current window.location before redirecting the user to login. After login is completed, adal takes the user back to where they were when login process was started.

In your case, user browses to "welcome" state => "localhost:port/". This transition user to "home" state using $state.go("home") but the browser url or window.location is still  "localhost:port/", which gets saved by adal before starting the login. And that is why user is taken to welcome page after login.

The fact that updating redirectUrl does not make any difference is because, the start page (from where login started) takes priority. There is a PR already submitted to configure the behavior of redirecting the user back to start page optional and always redirect them to the "redirectUrl" property. We will definitely consider that.

Can you try this: Instead of $state.go('home'), try $location.url('/home'). This will update the window.location value and save /home as start page instead of /welcome. Let me know if that does not work.

**Comment by alan994** [comment]
Thanks, it's working now :)
