### ISSUE TITLE
Token renewal operation failed due to timeout

### ISSUE THREAD

**Issue by jjcollins53** [AzureAD/azure-activedirectory-library-for-js#391]
I have a javascript file running in a SharePoint Online teamsite. It makes a call to a custom RESTful Web API secured by Azure AD. The Web API provides full CRUD operations for a corp database. The call to acquireToken fails giving the following error: Token renewal operation failed due to timeout. I have not been able to resolve this.

**Comment by ssrslm** [comment]
I'm also getting the same error, please help me if some body fixed this issue

![adal error](https://cloud.githubusercontent.com/assets/4487138/18698954/a918872c-7feb-11e6-9c00-4ca2a4e3fb89.png)

**Comment by tushargupta51** [comment]
@jjcollins53 @ssrslm Adal waits for 6 seconds to receive response from AAD. If AAD does not send a response at all or response was not send as fragment, adal cancel the request giving the above error. Can you please check the network tab (in Developer Tools in Chrome) or fiddler to see if AAD returned a response to adal request. adal request is sent to login.microsoftonline.com and starts with authorize?.

**Comment by jjcollins53** [comment]
Here is request/response:
[36_Request.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/485769/36_Request.txt)
[36_Response.txt](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/485772/36_Response.txt)

**Comment by jjcollins53** [comment]
Here is the code. I'm calling getCachedUser just before acquireToken. The cached user is always found, yet I'm still getting this error.

LinksLoader.deleteOldPTCSiteLinks = function () {
    "use strict";
    var $s = jQuery.noConflict();

    var userId = _spPageContextInfo.userLoginName;
    LinksLoader.ptcUserId = userId.substr(0, userId.indexOf('@'));
    var linkTimeStamp = new Date();
    LinksLoader.ptcLinkTimeStamp = linkTimeStamp.toISOString();

    // Assign variables
    var variables = {
        // Domain of Azure AD tenant
        azureAD: PTCConfig.azureADDomain,
        // ClientId of Azure AD application principal
        clientId: PTCConfig.ptcSiteLinkAPIClientID,
    }

    // Create config and get AuthenticationContext
    window.config = {
        tenant: variables.azureAD,
        clientId: variables.clientId,
        postLogoutRedirectUri: window.location.origin,
        endpoints: {
            ptcSiteLinksUri: PTCConfig.ptcSiteLinkEndpoint,
        },
        cacheLocation: "localStorage"
    };
    var authContext = new AuthenticationContext(config);

    var isCallback = authContext.isCallback(window.location.hash);
    authContext.handleWindowCallback();

    if (isCallback && !authContext.getLoginError()) {
        window.location = authContext._getItem(authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
    }

    var user = authContext.getCachedUser();
    if (!user) {
        authContext.login();
    }



    // Get site links of current user with AuthenticationContext of PTCSiteLinks API
    authContext.acquireToken(config.endpoints.ptcSiteLinksUri, function (error, token) {
        if (error || !token) {
            console.log("ADAL error occurred: " + error);
            return;
        }
        else {

            //var filesUri = "https://localhost:44321/odata/PTCSiteLinks?$select=Id&$filter=UserId eq '" + LinksLoader.ptcUserId + "' and Source eq '2016'";
            var filesUri = PTCConfig.ptcSiteLinkAPIUrl + "/odata/PTCSiteLinks?$select=Id&$filter=UserId eq '" + LinksLoader.ptcUserId + "' and Source eq '2016'";

            $s.ajax({
                type: "GET",
                url: filesUri,
                headers: {
                    "Authorization": "Bearer " + token
                }
            }).done(function (response) {
                console.log("Successfully fetched deleted PTC site links.");
                var items = response.value;

                for (var i = 0; i < items.length; i++) {
                    var deletePTCSiteLink = {
                        Id: items[i].Id
                    };
                    LinksLoader.deletePTCSiteLinks.push(deletePTCSiteLink);
                }

                var ajax_caller = function (data) {
                    return $s.ajax({
                        url: data.url,
                        type: data.type,
                        headers: {
                            "Authorization": "Bearer " + token
                        },
                        success: function () {
                            console.log("Successfully deleted PTC site link.");
                        },
                        error: function () {
                            console.log("Failed delete PTC site links.");
                        }
                    })
                };

                var ajax_calls = [];

                for (var i = 0; i < LinksLoader.deletePTCSiteLinks.length; i++) {
                    ajax_calls.push(ajax_caller({
                        url: PTCConfig.ptcSiteLinkAPIUrl + "/odata/PTCSiteLinks(" + LinksLoader.deletePTCSiteLinks[i].Id + ")",
                        type: "DELETE"
                    }));
                };

                $s.when.apply(this, ajax_calls).done(function () {
                    //alert("Old PTC Site Links deleted!");
                    LinksLoader.getFollowedLinks();
                });

            }).fail(function () {
                console.log("Fetching deleted PTC site links failed.");
            });
        }
    });
}

**Comment by ssrslm** [comment]
This error thrown once access token got expired, for first time (after clear browser cache) it is working well but this error keep throwing if I close and open the website after some time, again it is started working if l clear browser cookie, this is my angular adal config code

 ```
adalProvider.init(
       {
           instance: win.loginUrl,
           tenant: win.tenant,
           clientId: clientId,
           extraQueryParameter: 'nux=1',
           endpoints: endpoints,
           cacheLocation: 'localStorage'
       },
       $httpProvider
       );

        //To fix, infinite loading issue
        window.isAdalIFrame = win !== win.parent;
        console.info('isAdalIFrame', window.isAdalIFrame);
        if (window.isAdalIFrame) {
            console.info('No loading inside iFrame, stopped.');
        } else {
                 $urlRouterProvider
                .when('wizard', '/wizard')
                .otherwise('/');
        }
```

Do we require to do any other code check to verify that user is logged or not?

**Comment by jjcollins53** [comment]
As I mentioned, I authenticate by first logging into SharePoint Online. Are the auth cookie created by SharePoint valid when ADAL does the silent sign-in? I issue a getCachedUser and it succeeds, but acquireToken fails.

**Comment by stuartlong** [comment]
Anecdotally, we went from seeing 0 instances of this error to seeing it in a non-0 percentage of our sessions that coincided *exactly* with us upgrading from **1.0.11** to **1.0.12**

**Comment by tushargupta51** [comment]
@jjcollins53 Apologies for the delay on this, somehow this issue got dropped off the radar. I looked at the logs and from the logs it seems that the cookie was expired.

The `getCachedUser` or `getUser` methods look into the browser storage for id_token and returns a non-null user if there is a token inside the cache. It does not look into the token expiration time though.

What's happening here is since localStorage is used, tokens are preserved in the cache when one re-opens the browser (and hence getCachedUser returns a non-null object) but the AAD cookie is expired (unless user checked the `keep me signed in` checkbox when logging in). Since the cookie is expired, acquire token call fails with the "login required" error.

Instead of checking getCachedUser(), you can call getCachedToken(<clientID>) to check if there is valid idToken in the cache or not and call the acquireToken method or login method accrodingly.

I will add this issue to next milestone to investigate whether the logic inside `getCacheUser` and `getUser` needs to be updated.

**Comment by slobshay** [comment]
Hi, I also ran into this problem.
It happens only on IE (this is the most used browser for our testing).
When checking this on other browsers, authentication works fine.

The timeout occurs when using acquireToken, note that even when I try a login right after this failure, I still fail the next time I try acquireToken although login is successful.

This had happened before in my app, couldn't find any special reason for it, waiting for some time (usually the next working day) seem to solve this behavior.

Attached the output of the network tab of IE debugger:
![networkofbadrequest](https://cloud.githubusercontent.com/assets/23480382/21420135/89a47978-c834-11e6-8020-fd82d0f8a78a.png)

**Comment by maheshp9** [comment]
I am facing similar issue and also started happening after we updated our SDK to 1.0.12 last October. Any luck with narrowing down the root cause and a fix?

**Comment by tushargupta51** [comment]
Starting in 1.0.12, Adal added timeout to acquireToken method. It waits for 6 seconds to receive response from AAD for a given acquire token request. If no response is send within this time, adal sends this timeout error to the application. There are several reasons this might happen:

1. **Using Plain Js (non-angular)**: Ensure that `adal.handleWindowCallback` method is called when AAD sends the response to `redirectUri`. Whatever code is executed when the `redirectUri` page is loaded should ensure that handlewindowcallback method is called.

2. **Invalid RedirectUri**: If redirectUri is not one of the registered redirectUris, then AAD will not send the response to the redirectUri, instead return html with error. Adal cannot process this html, hence return the timeout error since it did not receive any response in url fragements.

3. **LocationChangeHandler not getting called when using angular**: Please ensure that locationChangeHandler in adal-angular.js is being called with the response from AAD. If that is not being called, then something is wrong. Providing logs and traces can help us find the issue.

**Comment by tushargupta51** [comment]
If you run into this specific error and none of the above helps, please open a separate issue with relevant logs, traces and we will look into that.

**Comment by nickaranz** [comment]
I keep getting this error when running my web part from a SharePoint context. Auth works fine from the local workbench (E.g : https://localhost:4321/temp/workbench.html) but I get the time out error as soon as I test it on a SharePoint site workbench (https://mysite.sharepoint.com/_layouts/15/workbench.aspx) - Also, as @slobshay mentioned, the error seems to go away on its own sometimes. I've made sure this is not a cache issue related to getCachedUser vs getCachedToken. I am using session storage and this fails even when it is the first time I am logging in. I have also triple check I have all the reply URLs added to my app registration in Azure AD. Any help or suggestions would be greatly appreciated. PS: I have applied this prototype overrides for SPFx web parts to the AuthenticationContext : https://dev.office.com/sharepoint/docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part/#make-adal-js-suitable-for-use-with-sharepoint-framework-web-parts

**Comment by RehanSaeed** [comment]
I've been getting this error intermittently (More details [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/532) using angular). Regarding the 3 points in the FAQ:

1. I'm using Angular, so this does not apply.
2. My RedirectUri is correct.
3. This is a poor description that does not tell me what the `locationChangeHandler` is, why I need to call it, where to call it etc.

I've downgraded to 1.0.11 for now but that's not a long term solution.

**Comment by ashishtechie** [comment]
@tushargupta51 and @RehanSaeed, do you guys found any solution to this, I am having the same issue and also, i can see in my case locationChangeHandler is not called since i am on Angular 4.x and which doesn't provide the events that seems like adal-angular expects. So, apparently this is never called. Can Adal-angular be supporting angular.2.x and above versions natively?

**Comment by ashishtechie** [comment]
I think I found a reason for IE, as it seems like IE is blocking the call to get token from microsoft. I am trying to add the microsoft login URL to trusted sites. But it doesn't seem to always work. Would update as i get it working.

**Comment by AlexUrbanAc** [comment]
I also have the issue "Token renewal operation failed due to timeout". I created a simple non-angular SPA example showing where I am stuck (using ExtJS framework, but the pure ADAL.js code in it should be framework-agnostic):

https://fiddle.sencha.com/#view/editor&fiddle/27oc
https://stackoverflow.com/questions/46561400/implement-adal-js-with-extjs-application

Do you have any ideas how to fix this?

**Comment by ashishtechie** [comment]
Update: for ie we had to add login.microsoft.com to trusted site and it worked. In first try I was not clearing everything in cache including favorites which was preventing trusted sites to work in a short span. This only applies to IE though.

**Comment by Sartor87** [comment]
We have experienced the following problem:
We had implemented Azure AD authenticated web API and we have been successfully had been making calls to it with ADAL 1.0.12 (we had our own wrapper around it for processing iframe for silent login). 

Now we got rid all together of our wrapper and upgraded to the latest version and started to get the problem described here: token renewal operation timed out.

The Azure AD architecture behind the API is very simple: a registered web app with Read directory data and Sign in and read user profile permissions. We have another native app registered with permissions to the web app (Access to the Web APP NAME HERE). Both applications have oauth2AllowImplicitFlow set to true in their manifests.

Both apps have registered a wildcard redirect URIs for https://ourtenant.sharepoint.com/* (we are making the calls from SharePoint to the web API). In addition, the native client app has registered redirect URI to the unique URI (App ID URI) of the web API app.

Both apps have been granted admin consent before - they were working fine with the old version of ADAL.js

So, here is some code. Please, note that we had tried both without displayCall callback (with page refresh directly on the current page) and with page refresh (check the commented code in initLogin method). Also we had a switch for generating a popup or an iframe with a callback on successful login.

The problem is with authContext.acquireToken. Note that if we call OurNamespace.authContext.getCachedToken(OurNamespace.clientId) we get a stored token for the resource.

Note that also, we are calling properly handleWindowCallback after each page refresh / iframe / popup.

Happens regardless of the browser.

` OurNamespace = {

        serviceMainUrl: "https://localhost:44339",
        webApiAppIdUri: "WEB-API-URI",
        tenant: "TENANT",
        clientId: "NATIVE-APP-GUID", // Native APP
        adalEndPoints: {
            get: null
        },
        adal: null,
        authContext: null,
        dummyAuthPage: null,
        usePopup: true,

        init: function () {
            this.dummyAuthPage = "DummmyLogin.aspx";
            OurNamespace.adalEndPoints.get = OurNamespace.serviceMainUrl + "/api/values";
            OurNamespace.authContext = new AuthenticationContext({
                tenant: OurNamespace.tenant + '.onmicrosoft.com',
                clientId: OurNamespace.clientId,
                webApiAppIdUri: OurNamespace.webApiAppIdUri,
                endpoints: OurNamespace.adalEndPoints,
                popUp: false,
                postLogoutRedirectUri: window.location.origin,
                cacheLocation: "localStorage",
                displayCall: OurNamespace.displayCall,
                redirectUri: _spPageContextInfo.siteAbsoluteUrl + "/Pages/" + OurNamespace.dummyAuthPage
            });
            var user = OurNamespace.authContext.getCachedUser(); // OurNamespace.authContext.getCachedToken(OurNamespace.clientId)
            if (user) {
                OurNamespace.azureAdAcquireToken();
            } else {
                OurNamespace.initLogin();
            }
        },

        initLogin: function () {
            //OurNamespace.authContext.config.displayCall = null;
            //var isCallback = OurNamespace.authContext.isCallback(window.location.hash);
            //OurNamespace.authContext.handleWindowCallback();

            //if (isCallback && !OurNamespace.authContext.getLoginError()) {
            //    window.location.href = OurNamespace.authContext._getItem(OurNamespace.authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
            //}

            OurNamespace.authContext.login();
        },

        displayCall: function (url) {
            var iframeId = "azure-ad-tenant-login",
                popup = null;
            if (OurNamespace.usePopup) {
                popup = window.open(url, 'auth-popup', 'width=800,height=500');
            } else {
                var iframe = document.getElementById(iframeId);
                if (!iframe) {
                    iframe = document.createElement("iframe");
                    iframe.setAttribute('id', iframeId);
                    document.body.appendChild(iframe);
                }
                iframe.style.visibility = 'hidden';
                iframe.style.position = 'absolute';
                iframe.src = url;
                popup = iframe.contentDocument;
            }
            var intervalId = window.setInterval(function () {
                try {
                    // refresh the contnetDocument for iframe
                    if (!OurNamespace.usePopup)
                        popup = iframe.contentDocument;
                    var isCallback = OurNamespace.authContext.isCallback(popup.location.hash);
                    OurNamespace.authContext.handleWindowCallback(popup.location.hash);
                    if (isCallback && !OurNamespace.authContext.getLoginError()) {
                        popup.location.href = OurNamespace.authContext._getItem(OurNamespace.authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
                        window.clearInterval(intervalId);
                        if (OurNamespace.usePopup) {
                            popup.close();
                        }
                        var user = OurNamespace.authContext.getCachedUser();
                        if (user) {
                            console.log(user);
                        } else {
                            console.error(OurNamespace.authContext.getLoginError());
                        }
                    }
                } catch (e) { }
            }, 400);
        },

        azureAdAcquireToken: function () {
            OurNamespace.authContext.acquireToken(OurNamespace.adalEndPoints.get, function (error, token) {
                if (error || !token) {
                    SP.UI.Status.addStatus("ERROR", ('acquireToken error occured: ' + error), true);
                    return;
                } else {
                    OurNamespace.processWebApiRequest(token);
                }
            });
        },

        processWebApiRequest: function (token) {
            // Alternatively, in MVC you can retrieve the logged in user in the web api with HttpContext.Current.User.Identity.Name
            $.ajax({
                type: "GET",
                url: OurNamespace.adalEndPoints.get,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                data: {},
                headers: {
                    'Authorization': 'Bearer ' + token
                },
                success: function (results) {
                    var dataObject = JSON.parse(results);
                    SP.UI.Status.addStatus("Info", "ADAL GET data success: " + dataObject.webApiUser);
                    $(".grid-info").html("<h1 class=\"h1\">Current Web API authenticated user: " + dataObject.webApiUser + "</h1>");
                },
                error: function (xhr, errorThrown, textStatus) {
                    console.error(xhr);
                    SP.UI.Status.addStatus("ERROR", ('Service error occured: ' + textStatus), true);
                }
            });
        }
    }`

**Comment by dvm-2k1** [comment]
Hi All, Is this issue got resolved? asking this question as we are also facing same issue of "Token renewal operation failed due to timeout" by ADAL when was call is happening with authContext.acquireToken() method. We also observe that every time when we browse our SharePoint site we get this error in order to call a WebAPI. It also throws "User login required" error when we tried to access the WebAPI even when we get user token by using "authContext.getCachedUser()". 

Please help us out if someone has any resolution to fix this issue....

**Comment by lgadola** [comment]
I get the error "Token renewal operation failed due to timeout". 
Managed to successfully connect to MS Graph and Office365 with the same mechanism. (AcquireToken)
However, trying to connect to a simple WebApi App published in Azure throws this error.
Created a very basic WebApi with AAD Bearer auth for testing 
[angular5-adal-example.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1841321/angular5-adal-example.zip)
.
This is the Angular5 App for reproduction.

**Comment by indriesergiu** [comment]
I managed to fix the issue by using @tushargupta51 's 1st suggestion: using simple adal.js and calling `adal.handleWindowCallback` on every page load. The `handleWindowCallback` method will examine the URL and if it contains token information it will proceed to parse the URL response and call the configured callback for the token acquire operation.

I used the following code:
```javascript
	// Check For & Handle Redirect From AAD After Login
	var isCallback = authContext.isCallback(window.location.hash);
	authContext.handleWindowCallback();

	if (isCallback && !authContext.getLoginError()) {
	    window.location = authContext._getItem(authContext.CONSTANTS.STORAGE.LOGIN_REQUEST);
	}
```

**Comment by dave0688** [comment]
I'm facing the same issue and been trying to solve it for days. How can I solve this for an Angular 5 app? Do I have to call handleWindowCallback() in an interceptor so that it gets called everytime? I'm really kind of stuck on this.

**Comment by indriesergiu** [comment]
I'm afraid I don't have a lot of experience with angular 5 so I couldn't
say if interceptors are the right place. But I would say go ahead and try.
If that doesn't work try calling the handleWindowCallback() method from the
start of each controller.

But remember, this handleWindowCallback() works for simple adal.js
implementations. If you're using AdalAngular you need to make sure another
method is called.

**Comment by robert-wallis** [comment]
I've been able to easily reproduce this by manually setting the `sessionStorage['adal.expiration.key...............']` variable to a timestamp in the past.

**Comment by r-e-d-s-a-n-d** [comment]
Looks like the iframe is not redirecting properly. I was able to solve it by modifying the adalFrame function.

`
AuthenticationContext.prototype._addAdalFrame = function (iframeId) {
    if (typeof iframeId === 'undefined') {
        return;
    }
    
    this.info('Add adal frame to document:' + iframeId);
    var adalFrame = document.getElementById(iframeId);
    var self = this;
    ** added onload function **
var handleFrameCallback = function(){ if(adalFrame) self.handleWindowCallback(adalFrame.contentWindow.location.hash); }

    if (!adalFrame) {
        if (document.createElement && document.documentElement &&
            (window.opera || window.navigator.userAgent.indexOf('MSIE 5.0') === -1)) {
            var ifr = document.createElement('iframe');
            ifr.setAttribute('id', iframeId);
            ifr.setAttribute('aria-hidden', 'true');
            ** added sandbox attribute to prevent site from reloading, you only need the token **
            ifr.setAttribute('sandbox','allow-same-origin');
            ifr.addEventListener('load', handleFrameCallback, false);
            ifr.style.visibility = 'hidden';
            ifr.style.position = 'absolute';
            ifr.style.width = ifr.style.height = ifr.borderWidth = '0px';

            adalFrame = document.getElementsByTagName('body')[0].appendChild(ifr);
        }
        else if (document.body && document.body.insertAdjacentHTML) {
            document.body.insertAdjacentHTML('beforeEnd', '<iframe name="' + iframeId + '" id="' + iframeId + '" style="display:none"></iframe>');
        }
        if (window.frames && window.frames[iframeId]) {
            adalFrame = window.frames[iframeId];
        }
    }

    return adalFrame;
};
`

**Comment by filuna** [comment]
I was able to solve it using r-e-d-s-a-n-d solution!! Thanks, man!
 I had to do one small improvement - to remove contentWindow, since adalFrame already is contentWindow 

`var handleFrameCallback = function () {
            if (adalFrame)
                self.handleWindowCallback(adalFrame.frameElement.contentWindow.location.hash);
        }`

**Comment by jesuslpm** [comment]
@r-e-d-s-a-n-d This works! you saved my day! Thank you

**Comment by davelosert** [comment]
I also face this issue from within the Teams Mobile Client where I am trying to acquire a GraphAPI-Token. 

@r-e-d-s-a-n-d s workaround fixed it for me - even though I had to delete the line `ifr.setAttribute('sandbox','allow-same-origin');` as this caused an IFrame Error Message. 

Will there be a fix for this? 
Or will we have to wait for MSAL (which is also currently not working from within MSTeams)?
