### ISSUE TITLE
SEAMLESS single sign on with ADAL.js and ADFS

### ISSUE THREAD

**Issue by nigel-dewar** [AzureAD/azure-activedirectory-library-for-js#400]
Hi There, I had already asked about this but never got a clear answer, so asking again.

What I am trying to accertain is, is it possible to achieve SEAMLESS single sign on with ADAL.js and ADFS?

And when I mean SEAMLESS, I really mean, even if the user is bounced through the the ADFS login page, thier username and password will automatically be populated so they just click go or login or whatever and then they are logged in.

The reason I want this is, I dont want my users having to sign in a second time to an app, when they are already signed into thier windows machine in the corporate network. ADFS should be able to detect this right?

So here I am hoping that when my adal.js equiped SPA hits ADFS, things just go nice and dandy and the user does not need to re-enter thier creds. the SPA recieves back its token and everyone is happy.

Users outside of the network will be required to enter thier creds obviously.

Its this possible what I am asking/ or seeking to achieve ?

**Comment by davewoodward** [comment]
ADFS achieves single sign-on by creating a cookie in the browser so I don't think ADAL should have any impact on that part of the process.  If the user is already logged into the domain that the ADFS server is joined to then they should be bounced to ADFS and back to the application but should never be prompted for their credentials.  That being said, I am curious as to what version of ADFS you are using (or thinking about using) since anything prior to version 4.0 had pretty lightweight support for OAuth 2.0-related flows.

**Comment by nigel-dewar** [comment]
Hi Thanks for your reply.

I was planning on using ADFS 2016. OR windows 2016 server's ADFS I should say.

**Comment by tushargupta51** [comment]
@nigel-dewar Ad @davewoodward mentioned, if there is a valid authentication cookie in the browser that identifies a user's session with ADFS, user should not be asked to enter creds when adal redirects them to adfs login page. Just to clarify, username/password will not be populated but ADFS will look into the cookie and the session is still valid and all, it won't prompt the user for creds again.

**Comment by nigel-dewar** [comment]
Ok thank you. This makes sense. Cheers.
