### ISSUE TITLE
acquireToken callback does not executed when _renewIdToken is used

### ISSUE THREAD

**Issue by istrau3** [AzureAD/azure-activedirectory-library-for-js#446]
I have the following code in my application (note: this app is not in Angular, it is in Aurelia, so I am using the underlying adal.js directly):

```javascript
export default class Authenticator {

    ...
    
    acquireToken() {
        return new Promise((resolve, reject) => {
            this.authContext.acquireToken(this.authContext.config.clientId, (error, token) => {
                if (error) {
                    this.alertService.open('error', 'We are having trouble validating your login access. Please try logging out and back in to resolve this issue. If this problem persists please contact support.')
                        .catch(() => this.authContext.logOut());
                    reject(error);
                    return;
                }
                resolve(token);
            });
        });
    }
}
```

As you can see, the Authenticator has a simple function that calls through to the adal authenticationContext's acquireToken and essentially wraps it in a promise.

The issue that I am seeing is this:
When acquireToken gets its token from `getCachedToken` as can be seen here:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L503
and token is not null, my method works as expected. The callback is executed and resolves the promise with the new token.

However, when `getCachedToken` returns null, `_renewIdToken()` is used to obtain the toke as can be seen here:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L527
when this occurs my callback is never executed. 

In other words, every one of my apps network requests uses the acquireToken() method above as interceptor to add the token to itself. However, whenever a request is issued and `_renewIdToken()` used to obtain the token, the request never goes out because the interceptor promise is never resolved.

Looking through adal.js, I cannot find any code that should be calling back on a successful retrieval of the token by Iframe. I see this line:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L458
but that only calls it when there is an error...

Thanks in advance.

Edit:
I should add that in order to test this, I did something like the following:
```javascript
authContext.getCachedToken = () => {
            return null;
        };
```
and then placed a breakpoint on the line: `if (error) {` in the `acquireToken` method above. It is never called.

**Comment by tushargupta51** [comment]
@istrau3 
>Looking through adal.js, I cannot find any code that should be calling back on a successful retrieval of the token by Iframe.

You should call `handleWindowCallback` method to process the response. This method saves the token in the cache and calls the callback with the error or token.

**Comment by istrau3** [comment]
@tushargupta51 I don't think you understood the problem.

I am in fact using `handleWindowCallback` when I get the token initially. However, when I use the `acquireToken` method, I expect that the callback I pass in will be called with the new token. This does not happen after the successful retrieval of the token. 

I can't call `handleWindowCallback` after calling `acquireToken`. Check out the PR that I submitted, it has a fix. I think the solution will clarify the problem.

**Comment by tushargupta51** [comment]
@istrau3 
I looked at the PR. The `_callbackWithTokenOnStorageChange ` listener will be called everytime storage is updated (not just for the token but everytime application adds something to storage). The expectation here is that when iframe gets the token, process the response and saves the token in the cache, this listener is called, which then calls the callback, is that right?

If so, then I don't think you need to add this listener, because "process the response" means calling `handleWindowCallback` method, which is going to call the callback for you. `handleWindowCallback` must be called whenever AAD returns the response to `redirectUri`.

**Comment by istrau3** [comment]
@tugupta Respectfully, I still do not think you are understanding the issue here.

Firstly (this is mostly tangential to the main point), with respect to `_callbackWithTokenOnStorageChange` getting called every time there is a storage change, that is true. However, notice it only really does anything if `getCachedToken` returns a valid token (which means that the new token has been stored in local storage), then it removes itself. So, basically, the listener is listening for the first case of a valid token being added into local storage, calling back and then turning itself off.

On to the main point, I guess I will use some code to demonstrate. Suppose I have the following code:

```
authContext.acquireToken(resource, sendANetworkRequestWithValidToken);

function sendANetworkRequestWithValidToken(err, token) {
     if (err) {
          console.log(err);
          return;
     }
     //send request with token
}
```

This seems to be valid given the `acquireToken `method's signature (namely that it takes a callback that purports to return either an error or a token. However, the `acquireToken `method is actually a dodgy method, it only actually executes the callback it has been given 99% of the time. 1% of the time it never executes the callback. That is buggy behavior. I realize that the 1% of the time it is actually going back to microsoft and refreshing the token, however that is not available to the caller. The method should execute the callback regardless of how it obtains the token, that is the whole point of the method - namely, it will acquire the token for you and you don't need to worry about how it will get the token. With your solution (somehow calling `handleWindowCallback` after the calling `acquireToken `, I need to concern myself with the internals of `acquireToken `.

However, suppose I went with your suggestion to use `handleWindowCallback`, how exactly an I supposed to do that? Using the previous example:

```
authContext.acquireToken(resouce, sendANetworkRequestWithValidToken);
handleWindowCallback()
```

Will that work? No, of course not. `handleWindowCallback` will be executed before `acquireToken` is finished its work. How do you propose that I know when to execute `handleWindowCallback`? Additionally, even if I know when to execute it, it still isn't possible. This is because ADAL is using an iframe to make the refresh request, an iframe that I, as the caller, do not have access to (in order to handle the returning url). 

The main point thought is that the `acquireToken` method is buggy, it intermittently does not execute its callback. If a method takes a callback, it should execute it after it finishes processing **on every call**, I think that much is clear.

my PR solves this issue.

**Comment by tushargupta51** [comment]
@istrau3 Thanks for the explanation. I think I understand the issue pretty well.

Let me explain how `acquireToken` is supposed to work. This assumes users are using plain JS and not the adal-angular wrapper.
It first checks the cache and if a valid token is present, return that token to the user using the callback. We both agree that this scenario works fine.

In the other case, when ADAL has to go to AAD to get a new token, `acquireToken` method calls the appropriate renew method: `renewIdToken` or `renewToken`. These methods create the token request, creates an iframe (or use an existing one) that will send the request to AAD and registers the callback(passed to the acquireToken method) on the window object (look at the `registerCallback` method).  When AAD sends the response back either with token or error, it sends the response to the registered `redirectUri` (default is app's root page/window.location.href). When using plain JS, its application's responsibility to make sure that adal is running on the url corresponding to `redirectUri` and `handleWindowCallback` method is called with the url hash that contains token/error. For example, this is a sample that uses plainJS and in app.js, handleWindowCallback is called: https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi/blob/master/TodoSPA/App/Scripts/app.js#L22.

A little bit about `handleWindowCallback`: When using plain JS, this method MUST be called by application in order to process the response. The right place to call this method is usually the JS code that gets executed whenever `redirectUri` is loaded. See the sample above for an example. This method parses the hash added by AAD, saves the token in the cache and looks up the callback method registered earlier on the window object (this is the callback that was passed to acquireToken) and then calls the callback with the result.
In an event, when handleWindowCallback is not called or for some reason AAD did not return the response to `redirectUri`, adal waits for 6 seconds and then return a timeout error to the callback passed to acquireToken method (look at _loadFrameTimeout method).
If the callback is not called even then, then there might be some error, share the logs and traces and I will take a look

Your changes also assume that "something" has updated the cache with the new token. That "something" is handleWindowCallback. Since that method calls the registered callbacks, there is no need of adding the listener to the storage. 

`handleWindowCallback` is not an internal detail but a public method that developers should be aware of when using plain JS. If using angular wrapper, adal-angular takes away that responsibility by intercepting the location and route changes.

Let me know if you have any further questions or doubts, I will be happy to answer them.

**Comment by istrau3** [comment]
@tushargupta51 Thanks for the explanation. My app is calling `handleWindowCallback`  on load. 

Looking at the network and source tabs, I see a new iframe get created, a request go out to microsoft and then nothing (my callback is not executed, neither with an error nor with the new token). I would think that the reason for this is because `handleWindowCallback` is not running in the window, it is running in the iframe. 

So basically this is the order of events that are occurring (I think):

1) I call `acquireToken` from the window
2) ADAL creates an iframe and redirects it to microsoft (to obtain the token) using `redirectUri` = window.location.href.
3) Microsoft redirects the iframe back to my app which processes the token using `handleWindowCallback`
4) The app running in the iframe looks for a registered callback **in the iframe** and does not find one because there is not callback registered there, it is registered in the original window that called.
5) My callback never gets executed.

**Comment by tushargupta51** [comment]
@istrau3  The order of events is correct.

>The app running in the iframe looks for a registered callback in the iframe and does not find one because there is no callback registered there, it is registered in the original window that call

`handleWindowCallback` looks up for the callback method in window.parent instead of window: https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal.js#L978. So, it should be able to find it.

Please share console logs and I might be able to tell what's going on.

**Comment by istrau3** [comment]
@tushargupta51 Ah, ok I see. Thanks for the explanation. I have solved the issue. The PR is not necessary.

**Comment by RobinHerbots** [comment]
@tushargupta51 ,  @istrau3 ,

Just for fyi.
Also when you use adal.js with a module loader, the callback isn't called because window.AuthenticationContext is not set.  Maybe this can be added to the faq

```
import AuthenticationContext from "adal-angular";

window.AuthenticationContext = AuthenticationContext; //AuthenticationContext  should be available on the window. See AuthenticationContext.prototype.getRequestInfo
```

**Comment by kngrace** [comment]
@istrau3 I'm attempting to track down an odd behavior and would love your thoughts on my current hypothesis. 

You had mentioned that the callback method is attached to window.parent previously:
> handleWindowCallback looks up for the callback method in window.parent instead of window: https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/lib/adal.js#L978. So, it should be able to find it.

I'm working on a SPFX web part and using a ['patch' that applies the following changes to ADAL JS v1.0.12. ](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/web-parts/guidance/call-microsoft-graph-from-your-web-part.md):

1. All information is stored in key specific to the web part (see the override of the _getItem and _saveItem functions)
2. Callbacks are processed only by web parts that initiated them (see the override of the handleWindowCallback function)
3. When verifying data from callbacks, the instance of the AuthenticationContext class of the specific web part is used instead of the globally registered singleton (see _renewToken, getRequestInfo and the empty registration of the window.AuthenticationContext function)

My Hypothesis: I believe this patch overwrites the handleWindowCallback function in a way that disallows it to be found and triggered. In perfect pathway situations, no issue is found but when I encounter a similar issue as the original poster, my callback function is not being triggered. Sometimes we see a timeout error, but most times nothing happens.

Can you, or anyone else familiar, confirm or correct my hypothesis?

**Comment by kngrace** [comment]
Based on further testing, my hypothesis seems partially correct.

The handleWindowCallback override attempts to split on the incorrect delimiter (semi-colon) and works properly when updated to split on comma.

**Comment by MtarantoOa** [comment]
Hello guys!
Im using adal,js with the wrapper  "adal-angular": "^1.0.15"  in my **angular 2** application.

I add a guard in my app that check if the user isAuthenticated means that I have the userInfo and the accessToken.
This is how I get the value of that flag 
`    public get userInfo() {
        return this.context.getCachedUser();
    }

    public get accessToken() {
        return this.context.getCachedToken(this.configService.AdalConfig.clientId);
    }

    public get isAuthenticated() {
        return this.userInfo && this.accessToken;
    }`
Now after 1 hr the token get expired. So that flag will be false. So I add a function to call the  acquireToken of the adal.js

`reNewToken(): Observable<Response> {
        var adalContext = this;
        return new Observable<Response>(observer => {
            this.context.acquireToken(this.configService.AdalConfig.clientId, function (error, token) {
                // Handle ADAL Errors
                if (error || !token) {
                    
                    observer.error(error);
                }
                adalContext.context.handleWindowCallback();
                observer.complete();
                //adalContext.context.to = token;
                
            });
        });
    }`
Why my return is an Observable? Well I need to wait for the callback funtion get executed. If Im not wrong when that function get executed and no error means that the token has been updated, correct?
After all the previous discussion I understood that  I need to call the handleWindowCallback, is that correct too?

This is the code of my guard and the canActivate function:

` canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
        if (!this.adalService.isAuthenticated) {
            alert('Not authenticated!');

            return this.adalService.reNewToken().map(res => {
                return true;
            });
        } else {
               return true;
        }
    }`

Im not sure what Im doing wrong but this is not working for me. I get my app into an invalid state.

Hope I can get some help! 

Thanks in advance!

**Comment by Lecha1** [comment]
MtarantoOa canActivate will not wait until your observable returns a value and thats the problem you have! Use instead resolve.
