### ISSUE TITLE
Bug in getResourceForEndpoint method 

### ISSUE THREAD

**Issue by cranqcore** [AzureAD/azure-activedirectory-library-for-js#452]
In the resource mapping method at
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L932 ,
there seemingly is a regarding the retrieval of own backend links. 

the else block will always return the configured login resource if no anonymouse endpoints are defined there, but won't go into the return null case.

In my specific case this end in the following logs:
> VERBOSE: Url: /myapp/i18n/locale-de.json maps to resource: all
> login is in progress.
> Getting error in the response: {"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/spo/i18n/locale-de.json","params":"","headers":{"Accept":"application/json, text/plain, */*"},"data":"login in progress, cancelling the request for /myapp/i18n/locale-de.json"}

which messes with my current angular-translate implementation, and ends up in angular-translate not being able to function before the login was successful (if I interpret this correctly).

**Comment by tushargupta51** [comment]
@cranqcore Thanks for reporting this. The if...else logic needs to be fixed in that method.

Also, I think check for `anonymousEndpoints` should go above the check for host uri to be same as redirect uri.

Adding this to next milestone.

**Comment by tushargupta51** [comment]
@cranqcore Hi, I am sorry but I might have missed some details here. The `return null` statement at the end is actually obsolete and we will remove that since we treat all relative calls to be calls to backend of the app.

In your case, /myapp/i18n/locale-de.json is treated as call to your own backend, and hence loginResource aka clientId is being returned.

 You are seeing `Getting error in the response` error because login is in progress and any api request which requires a token is cancelled if a login is in progress.
