### ISSUE TITLE
Importing adal.js as a module breaks token refresh

### ISSUE THREAD

**Issue by sea1jxr** [AzureAD/azure-activedirectory-library-for-js#460]
There is some module loading code in adal.js, so I tried bundling it with webpack and "require"ing it.  everything seemed to work fine till I went to refresh and the code at https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/dev/lib/adal.js#L796 tried to see if the IFrame window.parent.AuthenticationContext was defined.  When importing as a module that property isn't defined.  At that point the rest of the code thinks that the state didn't match.

**Comment by RobARichardson** [comment]
Had the same problem here. Had to revert back to just including the libraries in my page via script tags using the CDN files.  Definitely not ideal.

**Comment by johnelliott** [comment]
Glad to see this! I may be having the same problem, investigating it just now :)

**Comment by rohitnarula7176** [comment]
@sea1jxr @RobARichardson @johnelliott I apologize for the late response. We have been busy working on build 2017 so could not respond in a timely manner. You are correct. I have made a fix for this issue in my branch https://github.com/AzureAD/azure-activedirectory-library-for-js/tree/rohitn/Issue_543. Could you guys try this out and let me know if the issue gets resolved. We will fix this in our next release which will be in a week.

**Comment by RobARichardson** [comment]
@rohitnarula7176 I just gave this a shot but I'm still having issues.  The specific issue I'm having is when I attempt to access a REST API endpoint that's configured w/ a different Azure AD clientId from my application's Azure AD clientId. When I attempt this, adal-js fails silently in the background and my request to this API is never sent even though I have the endpoint configured properly in adal's 'endpoints' config option.  This behavior doesn't happen if I reference adal & adal-angular via CDN instead of importing as a module.

**Comment by RobARichardson** [comment]
@rohitnarula7176 I initially had some problems but I believe they were on my end.  Looks like token refresh is working now.  Thanks for the fix!
