### ISSUE TITLE
getCacheUser and getUser methods in adal.js

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-library-for-js#471]
Investigate whether getCacheUser and getUser are correctly implemented or not. Currently, these methods look for an id_token in the cache and return user created from it (getCachedUser only returns cached user). When using localstorage, storage might still have the id_token even when user does not have a valid session with AAD. Investigate whether the logic inside these methods should also take into account expiration of id_token

**Comment by tushargupta51** [comment]
`getUser` method is expected to return the user from last known login session, it does not return the currently logged in user. Do not rely on the return value to decide whether user is logged in or not.

If at the bootstrap time, application needs to know whether user session is active or not, is to send an acquireToken request to get a token for `clientId`, if AAD returns error "login_required", application should call login() method. Applications should listen to `acquireTokenFailure` event to do that. Please use 1.0.13 and later versions for this.

**Comment by sliekens** [comment]
> If at the bootstrap time, application needs to know whether user session is active or not, is to send an acquireToken request to get a token for `clientId`

I'm implementing this right now and I think you forgot to mention that you need to do a `clearCacheForResource(clientId)` before doing `acquireToken(clientId)`

PS if you do `acquireToken` without doing `getUser` first then you always get `User login is required` because the cached `idToken` (if it exists) is not deserialized yet

so the proper flow is
1. `getCachedUser()`
   - this call is required because it has an important side-effect (initialize `_user`)
   - if null: start interactive `login();`
2. `clearCacheForResource(clientId);`
   - this removes the cached access token for `clientId` so the next acquireToken call has to talk to microsoftonline
3. `acquireToken(clientId);`
   - error: start interactive `login();`
4. user is now logged in
