### ISSUE TITLE
Silent exception in callback method 

### ISSUE THREAD

**Issue by Abrissirba** [AzureAD/azure-activedirectory-library-for-js#474]
In the method AuthenticationContext.prototype._loginPopup there is a setInterval that checks if the user is siged in yet or not. If the user is signed in and a callback method has been provided, the callback method will be called with the accessToken. Any exception thrown in the callback method provided by the developer will fail silent due to a try with an empty catch. This will result in an infinit loop. 

To start with, why is there a try catch here? What can go wrong? Second, why is nothing logged in the catch? 

             try {
                if (popupWindow.location.href.indexOf(registeredRedirectUri) != -1) {
                    if (that.isAngular) {
                        window.location.hash = popupWindow.location.hash;
                    }
                    else {
                        that.handleWindowCallback(popupWindow.location.hash);
                    }
                    window.clearInterval(pollTimer);
                    that._loginInProgress = false;
                    that.info("Closing popup window");
                    popupWindow.close();
                }
            } catch (e) {
            }

**Comment by rohitnarula7176** [comment]
@Abrissirba Thank you for pointing this out. We have a try catch here because when a user clicks login, we open a popup window and set its location to the authorization endpoint which lies in a different domain (https://login.microsoftonline.com) . Having this when we try to get popupWindow.location.href, it will keep throwing an error "DOMException: Blocked a frame with origin "https://localhost:44302" from accessing a cross-origin frame (https://login.microsoftonline.com"). If we have something in the catch block, it will create a lot of traffic with a list of these exceptions that I mentioned above so we don't log anything there. 
On loginSuccess/Failure the user gets redirected back to the app's root page or the configured redirectUri which lies in the same domain as the app which allows us to access its window location without a cross-domain exception. In our code we wait for this redirect response using a polling mechanism every 20 msec.
In order to fix the infinite loop condition, if you are using plainJS, we can put a try catch in the handleWindowCallback method which actually calls the callbacks instead of adding anything in the catch block above. Please let me know if this makes sense.

**Comment by Abrissirba** [comment]
Thanks for the very good explanation :) Would it not be better to only have this check
    popupWindow.location.href.indexOf(registeredRedirectUri) != -1
in a try catch block and the rest of the code outside?

    var hasRedirectedToRedirectionUri = false;
    try {
        hasRedirectedToRedirectionUri = popupWindow.location.href.indexOf(registeredRedirectUri) != -1;
    }
    catch(Exception ex) {}
    if (hasRedirectedToRedirectionUri) {
       ...

**Comment by rohitnarula7176** [comment]
@Abrissirba Doing it the way you suggested will fix the issue you mentioned but we will still have an issue with the code if popup is set to false. For instance, when the user logs in using redirect flow, after loginSuccess/Failure user gets redirected to the app's root page with the token received as the url fragment. At the time of redirect, the app gets reloaded and we have a code running on app.js which calls handleWindowCallback() which extracts the token from the url and sets its location back to the app's root page (from https://localhost:44302/#id_token= to https://localhost:44302/ ) and then calls the user defined callbacks . If there is a silent error in the callback the token would remain in the url as a fragment and it is not considered safe. Hence adding the catch block inside this method will fix all issues.
