### ISSUE TITLE
AADSTS50058 in Edge but not IE

### ISSUE THREAD

**Issue by gabbsmo** [AzureAD/azure-activedirectory-library-for-js#479]
I've removed my app and login.microsoftonline.com from trusted sites as this is the expected setup from most of our users. CROS requests then work in IE but not in Edge. Edge only works if I add the two domains to my truested sites. I'm using localStorage as storage for adal-angular 1.0.11.

EDIT: Cookies are set to "Do not block cookies" in Edge.

**Comment by tushargupta51** [comment]
@gabbsmo The expected setup is that both app and login.microsoftonline.com are in the same zone.

This is what we recommend (its in readme too)
If you put your site in the trusted site list, cookies are not accessible for iFrame requests. You need to remove protected mode for Internet zone or add the authority url for the login to the trusted sites as well.

**Comment by gabbsmo** [comment]
@tushargupta51 Since I removed both app and authority from trusted sites both are in the Internet Zone. Protected mode is not enabled. Why does this setup work in IE but not in Edge?

**Comment by tushargupta51** [comment]
@gabbsmo It's hard to say what might be happening? Can you share network/fiddler traces?

**Comment by gabbsmo** [comment]
@tushargupta51 I've attached fiddler sessions and console output from adal.js for both IE and Edge.

[adaljs_issue_479.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/780368/adaljs_issue_479.zip)

**Comment by tushargupta51** [comment]
@gabbsmo Cookies are not sent along with the request in case of Edge. One case I have where this might happen is when the Edge process setting the cookie is different than the one sending the request to AAD for token renewal. Can you capture full trace in Edge which also has the login request, that is setting the cookie?

Also, do you close the browser when running the app, that will delete the cookies if KMSI is not checked at time of login.

**Comment by gabbsmo** [comment]
@tushargupta51 I've attached fiddler trace from edge. I logged out before recording. The browser was never closed in this session and I still reproduced the error message. I've sent the password to the archive to tushargupta51@gmail.com.

[edge_fiddler_sessions_with_login.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/782646/edge_fiddler_sessions_with_login.zip)

**Comment by tushargupta51** [comment]
@gabbsmo As expected, the response (frame # 11) that is setting the cookie and the token request (frame 63) are using different Edge processes. You can see that under the process column in the trace. The former is in process 13504 and the latter is in 17120.

We have seen this earlier and from what I remember, Edge guys told us that cookies might not be shared between different processes. I will bring this to notice of Edge guys and will let you know what I hear back.

From Adal's perspective, there is nothing we can do at library level. Adal only creates the request url and set the iframe src to that. The fact that Edge does not send the cookies along because of different process is outside of scope of adal.

**Comment by tushargupta51** [comment]
Closing this since this is an Edge issue and out of the scope of adal library. Edge team has handled some of this issues in the next version to be released sometime this year, not sure if the team has publicly shared the dates yet.
