### ISSUE TITLE
Unwanted client side authorization

### ISSUE THREAD

**Issue by yentheo** [AzureAD/azure-activedirectory-library-for-js#499]
Since one of the latest updates, the endpoints were added (endpoints and anonymous endpoints).

We added our api-url as an endpoint with the client id: 'https://myurl.tld/api'
But, we also have anonymous endpoints in our API which sometimes can be something like https://myurl.tld/api/some-anonymous-endpoint
Because of the /api/ the adal library thinks this isn't an anonymous endpoint and wants to add the token. But we want to access this api method without being logged in, that's why it's anonymous, at this point Adal throws an error because it wants to add the token but we aren't logged in.

Even if it would check the anonymous endpoints first, I don't think this is wanted behaviour. I don't want my client-side-authentication library checking which end points I can visit or not. I just want it to add the token when it's available and I assume that my server will return an unauthorized when I don't have it.

**Comment by tushargupta51** [comment]
@yentheo 
>I don't want my client-side-authentication library checking which end points I can visit or not. I just want it to add the token when it's available

In order to attach the token, library needs to know whether the request being sent requires authentication or not. `endpoints` and `anonymousEndpoints` array enables developer to provide these values. I think your issue should be fixed in the latest version where we moved up the anonymous endpoints check. Let us know if that is not the case and provide us the console logs.

**Comment by tushargupta51** [comment]
Closing this for now. Let us know if you have any questions.
