### ISSUE TITLE
seamless SSO using adal.js

### ISSUE THREAD

**Issue by AnassKartit** [AzureAD/azure-activedirectory-library-for-js#664]
Hi,
We have two azure webapps that use adal.js , 
web1
web2

when the user access the first web1 ,  he is asked for authentication and redirected, when he access web2 he is receiving multiple redirects which disturbs the user experience which I think is an expected behavior. What is the solution to have seamless redirections and access multi ressources using the same token?

**Comment by rohitnarula7176** [comment]
@AnassKartit Sorry for the delayed response. Its not possible to issue the same token for 2 different web api's if thats what you are referring to. Multiple redirections occur because the library supports implicit flow where all token are received from the authorization endpoint via a redirect response (302) which causes the web app to reload. This is by design. Can you please elaborate?
