### ISSUE TITLE
AcquireToken renewal is inconsistent

### ISSUE THREAD

**Issue by vaibhavlakhotia** [AzureAD/azure-activedirectory-library-for-js#673]
I am using adal.js (1.0.15) in an aurelia based SPA.I have changed the default offset of two minutes to 3 minutes and used a window.setInterval method to call for token renewal every one minute. According to my understanding when we call AcquireToken() it first looks into  the browser cache by using getCachedUser().This will look for the id_token and return a non null user.But it doesnt check the token expiration time though.But between the time it requests for a new token and it gets the response,the token expiry time shows 0(in the browser console).The older token however stays in the browser cache untill the new one is received.
Hence in my application at times it refreshes the token and at times it fails the very first time.
As far as I know between the request and response for a new token from AAD,if the time exceeds 6 secs then adal sends timeout error.Is it this error that is the reason for the the failure or renewal of token?
Can someone suggest how can we handle the inconsistency.
Also when the token is renewed teher is no callback handler.So i have also used handleWindowCallback().

**Comment by rohitnarula7176** [comment]
@vaibhavlakhotia Sorry for the delayed response. When you call acquireToken(resource, callback), it calls getCachedToken(resource) internally which first checks if the token exists in the cache and if it is valid. Please see below:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/9d24c364e59424cf4378faba565a79b4b2313d16/lib/adal.js#L418
The error "Token renewal operation failed due to timeout" occurs when the time between the request and response from AAD exceeds 6 seconds. You can now increase this timeout by altering the _loadFrameTimeout property in the config object. Also we have mentioned this in the readme that you have to call handleWindowCallback on page load if you are using the plain AdalJs without the angular wrapper for adal to process the tokens received in the urlfragment via a redirect response. henadleWindowCallback api is responsible for calling the callback passed in the acquieToken function. I hope I have answered your questions. Closing this issue for now. Please reopen if you still face any issues.
