### ISSUE TITLE
login() changes break functionality with previous versions and incorrectly assumes adal-angular use

### ISSUE THREAD

**Issue by mmckenz** [AzureAD/azure-activedirectory-library-for-js#706]
As of adal.js v1.0.16, AuthenticationContext.prototype.login no longer accepts a loginStartPage parameter. This is breaking to anyone using this functionality to control the LOGIN_REQUEST storage value to redirect to after handling a window callback.

adal.js - v1.0.15 - AuthenticationContext.prototype.login = function (loginStartPage) {
adal.js - v1.0.16 - AuthenticationContext.prototype.login = function () {

It seems this parameter has been pushed to the Angular layer:

adal-angular.js - v1.0.15 - var loginHandler = function () {
adal-angular.js - v1.0.16 - var loginHandler = function (loginStartPage) {

The new adal-angular.js logic sets the loginStartPage parameter value as a new ANGULAR_LOGIN_REQUEST storage value. This storage value is then consumed by adal.js rather than taking a loginStartPage parameter. adal.js should not be depending on the adal-angular.js layer in this fashion. How are those using only the adal.js component supposed to set this value?

Whoever made these changes did not consider the use case of consuming only adal.js in a standalone fashion without adal-angular.js. This is a breaking change to existing behavior and prevents our update of adal.js.

**Comment by mmckenz** [comment]
Thanks. I see a few alternative approaches:

1. Similar to what you recommend, set CONSTANTS.STORAGE.LOGIN_REQUEST prior to calling handleWindowCallback().
-or-
2. Set CONSTANTS.STORAGE.ANGULAR_LOGIN_REQUEST prior to calling login().

I'm not clear as to why CONSTANTS.STORAGE.ANGULAR_LOGIN_REQUEST was added. The name alone suggests it's specifically for the adal-angular component when it looks to be a suitable alternative to the prior loginStartPage parameter.

Any reason not to:
1. Remove CONSTANTS.STORAGE.ANGULAR_LOGIN_REQUEST.
2. Have adal-angular set CONSTANTS.STORAGE.LOGIN_REQUEST instead.
3. Have the adal.js login() method respect any existing value of CONSTANTS.STORAGE.LOGIN_REQUEST when called.
?

**Comment by rohitnarula7176** [comment]
@mmckenz The reason we added this is because due to the recent changes in angular ui routing, the state change event was not saving the toState url correctly which was resulting in users landing at a different page then what they started from after a successful login. Please refer to the following issue for details https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/536. So we had to evaluate the toState manually and pass its url to AdalJs. The main reason for removing this parameter from login is that we plan to add other parameters like extraQueryParameter to the login method, users who do not want to pass loginStartPage will have to call login as login(null, extraQueryParameter) which is not a convenient syntax. To solve this issue, you can manipulate the loginStartPage by setting its property in the callback method passed in the config method. Please let me know if you have any more questions.

**Comment by rohitnarula7176** [comment]
@mmckenz Closing this issue. Please reopen if you have further questions.
