### ISSUE TITLE
Critical bug for aquireToken found in 1.0.16 release

### ISSUE THREAD

**Issue by kov-hans** [AzureAD/azure-activedirectory-library-for-js#712]
When aquiring a new token the code for saving the expected state in the _renewToken function was changed from
_window.renewStates.push(expectedState);_
to 
 _this._renewStates.push(expectedState);_

and when receiving the token in getRequestInfo  function the code for getting expected states was changed from
_var statesInParentContext = window.parent.renewStates;_
to 
_var statesInParentContext = this._renewStates;_

but this.renewStates is empty, and that is the bug, it should contain the expected state. I guess this is caused by the iframe context.

**Comment by rohitnarula7176** [comment]
@kov-hans There is no bug in the library. We save the states on the adal instance on the parent window before we make the acquireToken call and when we receive the response in the iframe window, we use the code below to get the renewStates from the adal instance from the parent window.
```
else if (window.parent && window.parent._adalInstance) {
                self = window.parent._adalInstance;
            }

            var requestInfo = self.getRequestInfo(hash);
```
I am assuming you are using a third party angular wrapper and that wrapper needs to be updated with the current version of adal js. I have closed several issues regarding this. Please look at #701

**Comment by kov-hans** [comment]
But if the wrapper needs to be updated in order to work there is a breaking change between 1.0.15 and 1.0.16. Minor updates should not cause wrapper to fail, right?

**Comment by vjhbtigoyal** [comment]
I am also getting exact same error while using version 1.0.16 and above. When i debugged version 15 and 16, i also noticed same issue with renewStates. It works fine with version 15.
Is there some breaking change in this upgrade which the wrappers have to take care for seamless integration?
I am using ng2-adal/ng4-adal wrapper. Both are failing with version 16 and 17.

Kindly let us know.

Thanks,
Vijay

**Comment by rohitnarula7176** [comment]
@kov-hans The ng2-adal wrapper has written their own version of a public api which is exposed by Adal (handleWindowCallback). Please refer to this code below:
https://github.com/sureshchahal/angular2-adal/blob/266e93ef3bac374e005f814c0044dac67e6b5cb7/src/services/adal.service.ts#L63
Instead of writing their own implementation, they simply need to call adal’s public api like they do in other methods of their wrapper and everything should work as expected. This is not a breaking change as the library can change its own internal implementation as long as the public api's stay unaffected. Closing this issue as this seems to be an issue with the ng2-adal wrapper.
