### ISSUE TITLE
URI params gets cleared

### ISSUE THREAD

**Issue by tscislo** [AzureAD/azure-activedirectory-library-for-js#720]
I have some filtering parameters passed as URI params ?filterA=xxx&filterB=yyy, which when I copy and paste to new browser tabs gets cleared by adal-angular. When I disable adal-angular those URI params don't get cleared.

**Comment by cobaltsoftware** [comment]
What do you mean by "gets cleared by"?

**Comment by tscislo** [comment]
Here is the scenario
1. I'm using adal-angular5 which uses adal-angular on SPA
2. I log in on page: http://localhost:4200/something successfully 
3. I use app normally and navigate to http://localhost:4200/something?filter=A
4. When I copy paste http://localhost:4200/something?filter=A to another tab I get authenticated properly as I should, because I have active session in this browser, however during a series of redirects query params such as filter=A gets removed and I'm landing on http://localhost:4200/something without filter=A

**Comment by cobaltsoftware** [comment]
I would check to make sure of a few things

1. The token is being saved, 
2. Your token is passed to the server with EVERY request
3. Your timeout has not expired.

Also remember, with SPA's, even updating part if the page requires the authorization token that was received at logon. And if the session is close to  expiration, it has to be renewed before it expires.

**Comment by rohitnarula7176** [comment]
@tscislo Url query params are not retained during redirection from AAD by design. This is is the reason we strip the query params from the login start page before redirecting the user to the authorization endpoint. Please see below: https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/beee84cb37d59b04f15e06140d3c3dc1d61cade9/lib/adal.js#L171
You will have to save the query params elsewhere and then reset the window.location after successful authentication.
