### ISSUE TITLE
Use the 'state' parameter not possible.

### ISSUE THREAD

**Issue by viganella** [AzureAD/azure-activedirectory-library-for-js#725]
When I go to config and add 'state' parameter which according to Micorsoft documentation is: 
"Value included in the request that also will be returned in the token response. It can be a string of any content you want. A randomly generated unique value typically is used to prevent cross-site request forgery attacks. The state also is used to encode information about the user's state in the app before the authentication request occurred, such as the page or view the user was on", IS NOT SUPPORTED.

**Comment by nehaagrawal** [comment]
Hi viganella, I assume you are referring to this document [https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-code]. We do generate state parameter in our code to prevent cross-site request forgery attack. Can you please elaborate more about your issue? Do you want to send the state parameter yourself instead of the one provided by ADAL library?

**Comment by viganella** [comment]
Hi @nehaagrawal , yes I am referring to that document. I saw that you provide your own generated 'state' parameter, but I think you should allow us to provide our own state parameter.
If you refer to aforementioned Microsoft document it is says that 'state' is ALSO used to: "... encode information about the user's state in the app before the authentication request occurred, such as the page or view they were on". And this is exactly where I need the state parameter.
Specifically I have an ember app, that I need to know about this state (in my case a specific ID). So the user is accessing a state (specifically project/projectId), if they are not authenticated, they will be redirected to Azure portal for authentication and in this step the 'state' has to be passed too, so after authentication I can redirect the user to the state that I know I passed earlier. 
Would be great if we could add this possibility for the user of the library, so that we can have our own custom 'state' and this i believe is according to what Microsoft document mentions  too.

**Comment by nehaagrawal** [comment]
@viganella we have acknowledged this issue an an enhancement.

**Comment by viganella** [comment]
For the guys experiencing this, you can temporarily use a patch i did on my github. 
I will do soon a pull-request on this one.

**Comment by ewittry** [comment]
@viganella any update on this pull request?

**Comment by ewittry** [comment]
@nehaagrawal any update on this pull request?

https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/725

**Comment by sameerag** [comment]
This is fixed in `msal js`.
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
