### ISSUE TITLE
Token renewal operation failed due to timeout - get access token from web api

### ISSUE THREAD

**Issue by lgadola** [AzureAD/azure-activedirectory-library-for-js#730]
I get the error "Token renewal operation failed due to timeout".
Managed to successfully connect to MS Graph and Office365 with the same mechanism. (AcquireToken)
However, trying to connect to a simple WebApi App published in Azure throws this error.
Created a very basic WebApi with AAD Bearer auth for testing
[angular5-adal-example.zip](https://github.com/AzureAD/azure-activedirectory-library-for-js/files/1850890/angular5-adal-example.zip)

This is the Angular5 App for reproduction.

**Comment by sameerag** [comment]
This should be fixed in `msal js` latest versions.
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
