### ISSUE TITLE
ASP.NET Core 2 Angular 4 adal_angular issue - window not defined

### ISSUE THREAD

**Issue by bparkerhsd** [AzureAD/azure-activedirectory-library-for-js#739]
I am using the ASP.NET Core 2 Angular 4 template in Visual Studio 2017. When the code is in the AuthenticationContext (adal_angular4) function, a window.Logging statement is encountered. This results in a window not defined error. It appears the window object is not available. 

Is there way for this library to not use the window object?

**Comment by rohitnarula7176** [comment]
@bparkerhsd We already introduced a check in the library to check if the window object is undefined before we try to use it. Please see below:
https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/f20a0ddde2faef87f87aae8e6aafe4de2c6b7a50/lib/adal.js#L192

Are you using the latest version of the library. Also we have to use the window object as the library works receives all responses via a 302 response which reloads the webpage. In order to retain the app state we have to make use of the window object.
