### ISSUE TITLE
Use modern async programming practices

### ISSUE THREAD

**Issue by StevenLiekens** [AzureAD/azure-activedirectory-library-for-js#749]
Many of the APIs like `handleWindowCallback` are callback based. This approach to do async stuff is difficult to use and even more difficult to maintain.

```js
authContext.callback = function(errorDesc, token, error, tokenType) {
    if (error) {
        console.log('aw snap something went wrong: ' + errorDesc);
    } else {
        console.log('yay we got the token')
    }
}

authContext.handleWindowCallback();
```

Please add Promise based versions of APIs that emit some state when called.

```js
authContext.handleWindowCallback()
    .then(function(successResult) {
        console.log('yay we got the token');
    })
    .catch(function(errorResult) {
        console.log('aw snap something went wrong: ' + errorResult.errorDesc);
    });
```

Thanks.

**Comment by rohitnarula7176** [comment]
@StevenLiekens We cannot create a promise out of handleWindowCallback because of the nature of how a redirect response works. handleWindowcallback resets the window location after processing the hash which forces a app reload. If we had a promise in this, case, it will lose its state because of the app reload.

**Comment by StevenLiekens** [comment]
That's a good point that I hadn't thought about.
