### ISSUE TITLE
ADAL creates nested IFRAMEs when acquireToken is called

### ISSUE THREAD

**Issue by TheAifam5** [AzureAD/azure-activedirectory-library-for-js#765]
For me, happens when the ADAL configuration contains `endpoints`. ADAL creates an IFRAME which redirects then to the application, then application creates again IFRAME and so on 🗡 
More information here: https://github.com/grumar/adal-angular5/issues/43

ADAL Config:
```
{
  clientId: 'XXXXXXXXXXXXXXXXXXXX',
  postLogoutRedirectUri: location.origin,
  redirectUri: location.origin,
  instance: 'https://adfs.XXXXXXXXXXXX.XX/',
  tenant: 'adfs',
  cacheLocation: 'localStorage',

  // Map the location of a request to an API to a the identifier of the associated resource
  // "Enter the root location of your API app here, e.g. https://contosotogo.azurewebsites.net/":
  // "Enter the App ID URI of your API app here, e.g. https://contoso.onmicrosoft.com/TestAPI",
  endpoints: {
    'https://XXXXXXXXXXX.azurewebsites.net/': 'http://xxx/XXXXXXXXXXXXX'
  },
}
```

**Comment by TheAifam5** [comment]
Looks like downgrading to version 1.0.15 fixes that problem.

**Comment by husseinkorly** [comment]
I can see it happening in both versions ! I'm not using any wrapper package.

**Comment by sameerag** [comment]
This is fixed in `msal js`. Please try it and let us know.
All current authentication work from microsoft is delivered through `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We would recommend to move to `msal js` for any advanced feature asks.
