### ISSUE TITLE
Cannot read property 'getRequestInfo' of null

### ISSUE THREAD

**Issue by daoodk** [AzureAD/azure-activedirectory-library-for-js#768]
Found in AdalJS v1.0.17

Uncaught TypeError: Cannot read property 'getRequestInfo' of null
    at AuthenticationContext.handleWindowCallback (adal.js:1324)

At line 1315, this._openedWindows.length === 0.
At line 1320, windows.parent._adalInstance is undefined. 

Neither the if, nor the else if condition is met above, so 'self' remains null. 

Line 1324 calls self.getRequestInfo(hash) which fails. 

Interestingly, this.getRequestInfo(hash) returns a valid object at this point.

**Comment by nehaagrawal** [comment]
@daoodk  Please give us details about your use case and steps to reproduce. It's hard reproduce this issue by just looking at this error.

**Comment by ghost** [comment]
@nehaagrawal, I am encountering the same error whenever executing handleWindowCallback() from an iFrame. 

It appears that the problem is in AuthenticationContext.prototype.handleWindowCallback where the default value for the variable 'self' is set to null. In all other areas in the library, it is defaulted to 'this' instead. Changing to 'this' in my local copy resolved the issue.

**Comment by ghost** [comment]
@nehaagrawal, I believe the details provided above should provide the information you need to reproduce/investigate/resolve. Please advise if any additional information is required.

**Comment by jmckennon** [comment]
All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
