### ISSUE TITLE
After renew token app does not receive new token

### ISSUE THREAD

**Issue by MartineNavara** [AzureAD/azure-activedirectory-library-for-js#783]
I'm investigating an issue in our app where users are redirected to the home page after using the application for over an hour. I already learned that this is because of the redirectUri requires authentication. I therefore changed the redirectUri to a page that does not require any authentication.

After this change, the user is not redirected to the home page on token renewal, but the application can't perform any requests anymore. It appears that the app never receives the response from the iFrame with the new token.

During debugging I noticed that _renewStates is used to check if there is a stateMatch. The stateMatch is false, since the iFrame is handling the callback and does not have knowledge of the _renewStates set in the app itself. The callback from the request requiring a new token is also never called since the iFrame has no knowledge of the _callBackMappedToRenewStates set in the application. 

How can I make sure the callbacks from the application are called after receiving the new token?

**Comment by Teckden** [comment]
@MartineNavara here is a similar thread, there are few suggestions that helped me to understand the possible workaround to fix this https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/391

**Comment by dggsax** [comment]
@MartineNavara Hey there, I ran into this a few days ago with my Typescript React application. There are a few assumptions that the ADAL library makes that I'm addressing within Microsoft, but for now check out r-e-d-s-a-n-d's answer as that is what fixed my problem. It appears that the adal iframes are not doing anything when loaded, so adding the event listener to listen for `load` fixes that issue. At that point, then your requests to acquire access tokens _should_ work. Let me know otherwise!

**Comment by MartineNavara** [comment]
Thank you for your response. For now we are using v1.0.15, which does works as expected.

**Comment by nehaagrawal** [comment]
closing this issue since it's working.
