### ISSUE TITLE
Silent sign in iframe has size and disrupts page layout

### ISSUE THREAD

**Issue by harryhaomsft** [AzureAD/azure-activedirectory-library-for-js#849]
When ADAL.js creates the hidden iframe to acquire token, the iframe is still occupying a 4x4 space. And it causes page layout to change(scroll bars appear). It looks like the style of the iframe is set to visibility: hidden which only hides the element but does not remove the presence in the DOM. Using display:none should be able to fix this.

Repros on all browsers.

## Library Name
- adal.js

## Library version
Library version: 1.0.17

**Comment by bjaskj** [comment]
A quick hack for this while waiting for change is to use this CSS:
```css
[id^="adal"] {
  display: none;
}
```

**Comment by jmckennon** [comment]
This is a known bug in `adal js`, and is fixed in `msal js`. You can also use the workaround stated by @bjaskj for `adal js`. All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes. We recommend moving to `msal js` for any advanced feature requests and bugfixes.
