### ISSUE TITLE
Cannot find name 'AuthenticationContext'

### ISSUE THREAD

**Issue by qisirui99** [AzureAD/azure-activedirectory-library-for-js#869]
I'm using Angular7, and when I follow the below steps, It said can't find AuthenticationContext.
The step is
1. npm install adal-angular
2. import { } from 'adal-angular'; on my component
3. create config on my component
public config = {
    tenant: 'xxx',
    clientId: 'yyy',
    redirectUri: window.location.origin + '/auth',
  };
4. create the AuthenticationContext
this.authContext = new AuthenticationContext(this.config);

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Browser:
- [ x] Chrome version XX
- [ ] Firefox version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Safari version XX

## Library Name
- [ ] adal.js XX
- [ x] adal-angular 1.0.17

## Library version
Library version: 1.0.17

## Minimal reproduction of the problem with instructions

</code></pre>

**Comment by jmckennon** [comment]
Without seeing more of your exact code, it's a bit hard to debug what may be the problem here. We recommend following the exact basic steps on our wiki [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Config-authentication-context). Do you think you could provide more information if you're still seeing errors?

Additionally, we recommend everyone using `adal js` to make the switch to `msal js`. All current authentication work from Microsoft is delivered through the `msal js` library [here](https://github.com/AzureAD/microsoft-authentication-library-for-js). `adal js` is still supported only for security fixes, generally.

**Comment by jmckennon** [comment]
Closing this as we're assuming this is no longer an issue. We recommend that everyone switch to `msal js` [here](https://github.com/AzureAD/microsoft-authentication-library-for-js) for advanced features and bugfixes.
